### ISSUE TITLE
Weird bar jumps and double bars when switching windows

### ISSUE THREAD

**Issue by Dickby** [jdtsmith/indent-bars#11]
Reproduce like this:

Open a buffer with some code and enable `indent-bars-mode`,
`split-window-right`, now the bars in the inactive new window are not padded by the same amount,
when switching the focused window with `other-window` the bars in both windows change their position.

**Comment by jdtsmith** [comment]
This is documented [here](https://github.com/jdtsmith/indent-bars#per-buffer-stipple-offsets)?
