### ISSUE TITLE
Set only `:blend` in `indent-bars-highlight-current-depth`

### ISSUE THREAD

**Issue by aciceri** [jdtsmith/indent-bars#12]
Hey, great package! Finally one that has everything I always wanted.

I was wondering, is it possible to change only the `blend` factor for `indent-bars-highlight-current-depth`?
There is written that

>  At least one of :color, :face, :width, :pad, :pattern, or :zigzag must be set and non-nil for this setting to take effect.

My `indent-bars-color-by-depth` is `'(:regexp "outline-\\([0-9]+\\)" :blend 0.2)`
Currently I set `indent-bars-highlight-current-depth` to `'(:face default :blend 0.4)`, my goal is that colors remain the same but the the current depth highlight had a greater blend factor, instead now it uses the default face (with a greater blend factor).

I'm on the terminal if this is relevant somehow.

**Comment by aciceri** [comment]
How fast! I've tried but nothing to do :(
This is how I configured it:

```elisp
(use-package indent-bars
  :custom
  (indent-bars-color-by-depth '(:regexp "outline-\\([0-9]+\\)" :blend 0.2))
  (indent-bars-highlight-current-depth '(:blend 0.4))
  (indent-bars-no-stipple-char (string-to-char "┋")))
```

I'm on Emacs 29.1 (emacsclient in terminal). With this configuration the current depth "indent bar" doesn't show any difference compared to other ones:

![image](https://github.com/jdtsmith/indent-bars/assets/2318843/91877332-0287-4443-9205-aae796efcb28)

Instead doing as before I get this:

```elisp
(use-package indent-bars
  :custom
  (indent-bars-color-by-depth '(:regexp "outline-\\([0-9]+\\)" :blend 0.2))
  (indent-bars-highlight-current-depth '(:face default :blend 0.4))
  (indent-bars-no-stipple-char (string-to-char "┋")))
```

![image](https://github.com/jdtsmith/indent-bars/assets/2318843/aa35cc7d-bbfd-42c6-9927-829ce845830b)

**Comment by nicolasavru** [comment]
I wanted this feature also and it works fine for me with:
```
(setq indent-bars-color '(highlight :face-bg t :blend 0.5))
(setq indent-bars-highlight-current-depth '(:blend 1.0))
```

**Comment by aciceri** [comment]
Thanks @nicolasavru! With this now it works:
```elisp
(use-package indent-bars
  :custom
  (indent-bars-color '(highlight :face-bg t :blend 0.2))
  (indent-bars-highlight-current-depth '(:blend 0.4))
  (indent-bars-no-stipple-char (string-to-char "┋")))
```

But if I also set `indent-bars-color-by-depth` to `'(:regexp "outline-\\([0-9]+\\)" :blend 0.2)` it stops showing bars.
@jdtsmith On my side this can be closed now.

**Comment by jdtsmith** [comment]
Yes there are multiple blends and you have to read their docs carefully to understand the usage, since there are multiple effects (blend with frame background, blend with main color).

As you found, you need to set the main color's `:blend` differently from the standalone blend in `highlight-current-depth` ; formerly you had them the same.  BTW, if you set `indent-bars-color-by-depth` `:blend=0.2`, the colors are _very faint_.  The highlight still works, you can just barely see it.  You need a 24bit color terminal too btw.
