### ISSUE TITLE
Bad interaction with lsp-ui-sideline-mode

### ISSUE THREAD

**Issue by magthe** [jdtsmith/indent-bars#14]
I'm seeing some ugliness when I have both `lsp-ui-sideline-mode`and `indent-bars-mode` active. [^1]

![screenshot_2023-08-19_20-57-38_974020329](https://github.com/jdtsmith/indent-bars/assets/327270/567c2b63-ef56-4231-8c69-eed83a9e8107)

When I turn off stipple mode off, `(setq indent-bars-prefer-character t)`, the problem goes away.

I'm fully aware  this might be an issue caused by _lsp-ui_ rather than _indent-bars_, but I thought it's worth reporting it here first as I kind of suspect that the developers of _lsp_ui_ have minimal experience with stipples :grin: 

[^1]: https://www.reddit.com/r/emacs/comments/15vpd30/lspuisidelinemode_and_fonts/

**Comment by jdtsmith** [comment]
Character vs. stipple shouldn’t really matter. Is this on blank lines only?  What happens if you disable blank line display?

**Comment by magthe** [comment]
Ah, yes, removing bars on blank lines fixes it. Then I think I have enough information to raise a ticket on lsp-ui.

Thanks!

**Comment by jdtsmith** [comment]
They should be able to work together with some care.  The key is they need to consider display properties on the line.
