### ISSUE TITLE
Support for specifying which column to start counting indention?

### ISSUE THREAD

**Issue by Trisk3lion** [jdtsmith/indent-bars#16]
Hello!

A very nice package you have here!

I wonder if it would be possible to support setting a start column where the indention should start to be counted from, instead of 1?

The reason I ask is that i code in COBOL where the code starts at column 8. Right now it looks like this for me:
![image](https://github.com/jdtsmith/indent-bars/assets/9075125/3803e97f-c01c-4ed0-ad70-e6f8d1f79074)

`indent-bars-spacing` is 4, which is my indent but as you can see I get the first line at column 5 (which is I would like to be without) and then a line every 4 columns after that, so 9, 13 etc.

It would be great if I could set the start column to 8 and then have a bar at 8, 12, 16 etc.

**Comment by jdtsmith** [comment]
This is some strange indentation!  Columns in Emacs are zero-based BTW.  By default, if `indent-bars-spacing`=4, you'll get bars at C0, C4, C8, C12, ...  So it looks like you have content start at C7?  Why does Cobol do that?  

In an case, it seems what you really want is bars at C7, C11, C15, etc.  Is there a mode variable that controls the rest of the indentation spacing (4, here)?

I am working on an option for putting the first bar on C0 (some people want that).  I could generalize it to an `indent-bars-column-offset` for `t`=current default (skip to first indent level), NUM = some fixed column offset (i.e. 0 for people who like that, or 7 for COBOL buffers).   Does COBOL use tabs or spaces?

**Comment by jdtsmith** [comment]
Please check the dev branch, which has a new option `indent-bars-starting-column`.  I think `(sets-local indent-bars-starting-column 7)` in your Cobol-mode-hook (or wherever) should work.  Note that this version includes lots of other updates, including treesitter and tab support.  So please test it and let me know of any problems.

**Comment by Trisk3lion** [comment]
The reason why the content start at C7 for COBOL (on the Mainframe) is because in ancient times code where written on punch cards and in order to know the correct order of the cards the first column where reserved for line numbers. 
And then in the name of "backwards combability" it has stayed that way, at least when writing Cobol for the Mainframe.

I tried the "dev" branch, but there seems to be variable which is not declared at the moment;  `indent-bars-skip-leftmost-column` is used in `indent-bars--setup-font-lock` but not declared anywhere.

**Comment by Trisk3lion** [comment]
I'm using the [cobol-mode](https://elpa.gnu.org/packages/cobol-mode.html) from elpa with some of my own modifications, far from perfect but it works. It defines the variable `cobol-tab-width` which should be the number of spaces to indent with.

Unfortunately no, there is no tree-sitter for Cobol. I have been thinking of taking a stab at it myself but haven't gotten around to it. It is not a trivial language to parse  because of the various dialects and changes since it's inception.

**Comment by jdtsmith** [comment]
Did you see https://github.com/yutaro-sakamoto/tree-sitter-cobol?  I'll close this since it seems the specified column starts works well for this.

**Comment by Trisk3lion** [comment]
No I had completly missed that one! Very interesting, maybe an excuse to start working on a `cobol-ts-mode`!

It works perfectly for me now, thanks for implementing this and doing so quickly!
