### ISSUE TITLE
Doesn't look like expected on my setup: big dots

### ISSUE THREAD

**Issue by neurolit** [jdtsmith/indent-bars#17]
Hi!

I installed indent-bars using default configuration on Emacs 29.1 (no PGTK, on Linux) :
```elisp
(use-package indent-bars
  :elpaca (indent-bars :type git :host github :repo "jdtsmith/indent-bars")
  :hook ((python-mode yaml-mode) . indent-bars-mode))
```

It works, but not like expected: dots are very big!
![2023-09-09_17-24](https://github.com/jdtsmith/indent-bars/assets/1727830/703c6d73-8632-4542-8366-01ff6479c212)

I don't see any problem when I test stipples:
![2023-09-09_17-30](https://github.com/jdtsmith/indent-bars/assets/1727830/5d59171a-8410-4c0f-80ed-ec4607c2aa4e)

Do you know what could be causing it?

**Comment by neurolit** [comment]
In fact I'm not sure there is a problem. It doesn't look like default example, but it looks like the screenshot in the README.

**Comment by jdtsmith** [comment]
Looks reasonably close to the defaults, but everybody's font size is different.  Did you try changing `indent-bars-width-frac` and `indent-bars-pattern`?  BTW, what does `M-: (frame-char-height)` say?

**Comment by neurolit** [comment]
Evaluating `frame-char-height` says 30.

**Comment by jdtsmith** [comment]
OK, everything looks alright then.  There are plenty of options to play around to dial it in the way you like; check the examples.  I updated the figure to match the current defaults.

**Comment by jdtsmith** [comment]
I also renamed the example "Default" to "Old Default" to prevent similar confusion.  Thanks for the report.
