### ISSUE TITLE
Is there a way to skip certain indent bars on nested structures like arrays/dicts to function parameters?

### ISSUE THREAD

**Issue by Dima-369** [jdtsmith/indent-bars#18]
First of all, thank you for this amazing package with the treesitter integration. This brings Emacs closer to what I am used to in PyCharm 🙂 

I found a difference and I wondered if any kind of configuration so far can adjust this behavior:

It's best demonstrated with an example. Here is how PyCharm does its indent bars with a array/dict to a function call where it skips indent bars:

![CleanShot 2023-09-10 at 20 48 47](https://github.com/jdtsmith/indent-bars/assets/15002298/e0cf65d7-66a6-4f7f-8874-f437a39d1a9e)

It looks like this with `indent-bars-mode` enabled in Emacs:

![CleanShot 2023-09-10 at 21 45 03](https://github.com/jdtsmith/indent-bars/assets/15002298/cecfd297-1dc4-499e-96b0-73498f84384e)

Here is the text:

```python
if True:
    if True:
        foo = foo(a1='1',
                  a2=[{
                      "a": "b"
                  }],
                  looooooooooooooooooooooooooooooooooong=False)

```

**Comment by jdtsmith** [comment]
Thanks for this example; it revealed a slight misunderstanding I had in the treesit query interface I'm using.  Check the latest for a fix.  That said, right now I only style one more than the topmost matching node's beginning indent.  E.g. the `foo = ` line in this case.  So it should look like:

<img width="477" alt="image" src="https://github.com/jdtsmith/indent-bars/assets/93749/bd1cda45-d66f-40e7-940d-6bc1170ed8f3">

I don't have the capability to skip bars and then draw more.  Usually arguments get wrapped to line up with the opening paren, so it doesn't make as much sense to align to their start anyway.

**Comment by Dima-369** [comment]
> Check the latest for a fix.

Works as shown in your screenshot!

> I don't have the capability to skip bars and then draw more.

I suppose one could do it by using the same stipple color as the default background color? But maybe that's not reliable.

>  Usually arguments get wrapped to line up with the opening paren, so it doesn't make as much sense to align to their start anyway.

Visually, it's still a very cool feature when the structures start to nest, but definitely not a deal-breaker and nothing major 😉 

![CleanShot 2023-09-11 at 07 52 48](https://github.com/jdtsmith/indent-bars/assets/15002298/9c85422c-2795-4734-9192-aaff36370723)

**Comment by jdtsmith** [comment]
I don't mean visually, that wouldn't be hard.  It's how to calculate which bars to show, and where.  I could certainly find the innermost wrapping entity (list, dict, argument_list, etc.).  I guess I could look at the full set of wrapping entities of interest (if any), calculate each of their starting line indent levels, and include only those bars.  But this isn't even on a fixed spacing, i.e. depends on the length of the function name.   Not sure this one is worth it.
