### ISSUE TITLE
Showing bar for first level of indentation?

### ISSUE THREAD

**Issue by zovt** [jdtsmith/indent-bars#20]
Hello! Great package :) Not sure if this is a feature request or if I'm missing something in the options. Here's a visual example of what I'm currently seeing:

![2023-09-12_08-02](https://github.com/jdtsmith/indent-bars/assets/5061820/10487998-b76c-46b5-b58f-35a9a7505eca)

Is it possible to configure this package so that a bar is drawn for the "first" level of indentation? E.g. between the `fn` and the outermost `}`. Not a huge make or break one way or another, but it would be nice if this were an option. Thanks!

**Comment by zovt** [comment]
Sigh... immediately after opening this issue I saw `indent-bars-starting-column`. Sorry for the churn :sweat_smile:

**Comment by jdtsmith** [comment]
No worries, added an FAQ.
