### ISSUE TITLE
Feature request HSV mode

### ISSUE THREAD

**Issue by dov** [jdtsmith/indent-bars#25]
I just found out about indent-bar and I would like to color the indent in a HSV color scheme as follows:

1. The bars-color-by-depth causes a change in the (cyclic) hue by some divider, e.g. 8 or 10. The H and S are constant for all levels
2. The current depth causes a change in the S or the V value of the corresponding indent color. For example for a light theme, I may want default S to be 0.25 and for the current level it should be 0.75..

Is this currently possible?

**Comment by jdtsmith** [comment]
Something close should be.   Use `indent-bars-color-by-depth` and the `:palette` keyword (instead of `:regexp`).  `color-hsl-to-rgb` and `color-rgb-to-hex` can be used to get a list of color values for some set of hues to provide to this keyword.  Then play with blend for the current highlight.  When you have some settings you like let me know and I can add to the examples.

**Comment by dov** [comment]
Thanks! That makes sense for the `indent-bars-color-by-depth` variable. But that doesn't solve my point 2 above. I.e. how can I change only the S value for the current depth?

**Comment by jdtsmith** [comment]
First, did you try `:blend`?  A real advantage of that is it can accommodate various themes and backgrounds to make bars ~equally subtle.   

I just added the option of `:palette` to `indent-bars-highlight-current-depth` (b913264).  So something like this should be what you are after:

```elisp
(let ((pals (cl-loop for s in '(0.25 1)
		     collect
		     (cl-loop for h from 0.0 upto 1.0 by 0.1
			      collect
			      (apply #'color-rgb-to-hex (color-hsl-to-rgb h s 0.5))))))
  (setq indent-bars-color-by-depth `(:palette ,(car pals))
	indent-bars-highlight-current-depth `(:palette ,(cadr pals))))
```

<img width="459" alt="image" src="https://github.com/jdtsmith/indent-bars/assets/93749/d43039c3-445a-4755-a666-12223c22fed7">

**Comment by jdtsmith** [comment]
Let me know if this works on your end.

**Comment by dov** [comment]
Thanks! I have now tried it and it works great.

However, since I'm using a light mode I prefer using HSV instead of HSL, so my initailization now looks as follows:

```
(load "indent-bars.el")

(defun color-hsv-to-rgb (h s v)
  """Converts HSV to RGB.

  Args:
    h: The hue in degrees.
    s: The saturation, a value between 0 and 1.
    v: The value, a value between 0 and 1.

  Returns:
    A list containing the RGB values [r g b]."""

  (let* ((i (floor (* 6 h)))
         (f (- (* h 6) i))
         (p (* v (- 1.0 s)))
         (q (* v (- 1.0 (* f s))))
         (t_ (* v (- 1.0 (* (- 1.0 f) s))))
         (i (mod i 6)))
    (cond
     ((= i 0) (list v t_ p))
     ((= i 1) (list q v p))
     ((= i 2) (list p v t_))
     ((= i 3) (list p q v))
     ((= i 4) (list t_ p v))
     ((= i 5) (list v p q))
     (t (list 0 0 0)))))

(let
    ((pals (cl-loop for s in '(0.05 1.0)
		    collect
		    (cl-loop for h from 0.0 upto 1.0 by 0.125
			     collect
			     (apply #'color-rgb-to-hex
                                    (color-hsv-to-rgb h s 1.0))))))
  (setq indent-bars-color-by-depth `(:palette ,(car pals))
        indent-bars-pattern "."
	indent-bars-highlight-current-depth `(:palette ,(cadr pals))
        indent-bars-width-frac 0.25
        indent-bars-pad-frac 0.25))

(provide 'init-indent-bars)
```

Here is a a small example:

![nest](https://github.com/jdtsmith/indent-bars/assets/338235/017b231e-9b3a-4f8c-9832-60574e0dc225)

Thanks again!
