### ISSUE TITLE
Does not work for emacs-mac

### ISSUE THREAD

**Issue by fu123456** [jdtsmith/indent-bars#30]
It does not work well in my emacs-mac. I install emacs-mac by 
```sh
brew tap railwaycat/emacsmacport
brew install emacs-mac
```

I try to do M-x emacs-version, it shows
```txt
GNU Emacs 29.1 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2023-08-17
```
I enable "indent-bar-mode", but it does not change any thing.

**Comment by jdtsmith** [comment]
You are not running emacs-mac. It should say Carbon, not NS.

**Comment by fu123456** [comment]
Yes. I now use emacs-mac from https://github.com/railwaycat/homebrew-emacsmacport/releases . It does work! Thanks a lot.
