### ISSUE TITLE
Automatically `indent-bars-reset` when switching between themes

### ISSUE THREAD

**Issue by aciceri** [jdtsmith/indent-bars#31]
I just added the following to my config
```elisp
(advice-add 'consult-theme :after #'(lambda (&rest r) (with-eval-after-load 'indent-bars (indent-bars-reset))))
```

(I'm not sure if `with-eval-after-load` is really needed)

Indeed I switch between themes often (especially between a light and a dark theme) and I indent bars' colors were updating correctly.
I don't know `indent-bars` internals but I wonder why this is not the default (advising an emacs builtin like `load-theme` instead). Has it any caveat I'm not considering?

**Comment by jdtsmith** [comment]
There is strangely no published hook for theme changes.   I think there should be; perhaps submit it as a bug report? In the meantime, the right way to do it is to add advice to load-theme on indent-bars load (e.g. in use-package :config).

**Comment by aciceri** [comment]
Yeah I agree that an hook should exist, Prot's solution is more versatile than mine. So I guess that you are waiting for this to be in Emacs itself before implementing something that automatically calls `indent-bars-reset` when a new theme is loaded?

Feel free to close in that case.

**Comment by jdtsmith** [comment]
Yes implementing it as advice is a maintenance issue.   A hook should exist for many other modes, so please do M-x report-emacs-bug.  Do you want to propose some documentation?

**Comment by aciceri** [comment]
@jdtsmith Sorry for never answering this. I'm using the following right now:
```emacs-lisp
  (defvar after-enable-theme-hook nil
    "Normal hook run after enabling a theme.")

  (defun run-after-enable-theme-hook (&rest _args)
    "Run `after-enable-theme-hook'."
    (run-hooks 'after-enable-theme-hook))

  (advice-add 'enable-theme :after #'run-after-enable-theme-hook)
  
  (add-hook 'after-enable-theme-hook #'indent-bars-reset)
```

For some reason if I put the hook inside the `use-package`'s `:hook` "stanza" it doesn't work anymore.

> please do M-x report-emacs-bug

Will do it as soon as I understand how the GNU bugs tracker works (first time using it)

> Do you want to propose some documentation?

Sure! Do you mean in the wiki or in the README? The snippet above with a bit of context on what it does and why it's needed is enough?

**Comment by aciceri** [comment]
Just sent a report with `report-emacs-bug`, added you in CC.

**Comment by aciceri** [comment]
I reported [that](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69651) and they told me that actually such an hook exists since `29.1`, indeed I'm successfully using this now.

```elisp
(add-hook 'enable-theme-functions #'(lambda (&rest _) (indent-bars-reset)))
```

Would you want me to send a PR doing this? In that case can I simply assume that everybody is at least on `29.1` or do you prefer a check?

**Comment by jdtsmith** [comment]
Thanks.  In fact I've added a similar thing to another mode of mine so I'll do so here.

**Comment by jdtsmith** [comment]
Closed in 4583e3e; please remove your config and give it a test.

**Comment by aciceri** [comment]
Just tried, it works! (I'm on `30.0.50`)

**Comment by jdtsmith** [comment]
For now I've disable `enable-theme-functions` support since it was causing more trouble than it solves.  v0.5 will correctly handle this.
