### ISSUE TITLE
Error after updating to 2.2

### ISSUE THREAD

**Issue by walseb** [jdtsmith/indent-bars#32]
Hello!

I just updated to `indent-bars` 2.2, and I keep getting the following error when I first enter a file. After that initial error, it never happens in that file again, and `indent-bars` works perfectly.

```lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p (13))
  indent-bars--update-current-depth-highlight((13))
  apply(indent-bars--update-current-depth-highlight (13))
  timer-event-handler([t 26006 13819 337310 nil indent-bars--update-current-depth-highlight ((13)) nil 506999 nil])
```

I'm getting this on a config that's far from vanilla.  Can you deduce what the issue is from the backtrace alone? If not, then I will have to dissect my config to find the possible interference, or manually ignore this error. Looks like the timer function is passing a list where a number is expected for whatever reason.

I suppose that you aren't getting this, so it could be an issue with my config. Or maybe I'm only seeing it because I have `debug-on-error` enabled?

Thanks for any help!

**Comment by jdtsmith** [comment]
Good catch, I had a mistake with the new timer functionality for current depth highlighting.  Please update to 0.2.3 and let me know if that fixes it.

**Comment by walseb** [comment]
Hello! 

I tested 2.3 and it works perfectly. 

Thanks so much!
