### ISSUE TITLE
[Question] How to contribute to the wiki?

### ISSUE THREAD

**Issue by ethanxxxl** [jdtsmith/indent-bars#33]
I just set up this package, and so far it has been working great! I wanted to share my c-mode tree-sitter wrap settings on the wiki, but can't figure out how to make a pull request for it.

I made another page that documents some of the issues I ran across and resolved while setting up indent-bars/treesitter. I figured that if I had these issues, other people might run across them too.

**Comment by jdtsmith** [comment]
Oops, I hadn't enabled public editing on the Wiki; you should be able to just make your changes now.  Thanks for contributing!  For your general tree-sitter issues, perhaps add those to another sub-section at the bottom if you like.
