### ISSUE TITLE
Bars are not showing in tree-sitter based modes (or normal), even that the indent-bars mode is enabled

### ISSUE THREAD

**Issue by sfmb-mx** [jdtsmith/indent-bars#34]
Hello, really love this idea!

I followed all the instructions as usual for the installation, my setup using straight is:

![2024-01-09_19-27](https://github.com/jdtsmith/indent-bars/assets/4007115/fbcc0dbf-6500-49e9-b579-b2606f30d883)

I really like the idea of high performance indentation, can you please clarify how to use with tree-sitter and normal modes? In this moment three modes are important to me: python-ts-mode, yaml-ts-mode and elm-mode.

I made all the compatibility tests in an arch box with GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) and everything is ok.

![image](https://github.com/jdtsmith/indent-bars/assets/4007115/8fb008fe-e987-40e1-acd3-8853bd12d076)

Any advice to activate your package?

thank you in advance.

**Comment by jdtsmith** [comment]
The test shows no bars. Please read the Compatibility section of the README.
