### ISSUE TITLE
Extra indent bars might be mistakenly drawn on wrapped lines

### ISSUE THREAD

**Issue by taquangtrung** [jdtsmith/indent-bars#38]
Hi,

Thank you for providing this great package! It works very fast on even a large file of 10KLoC.

I encountered a small issue when using this package with [word-wrap](https://docs.doomemacs.org/v21.12/modules/editor/word-wrap/) mode of Doom Emacs. I noticed that `indent-bars` might mistakenly draw the indentation bars on the wrapped lines.

For example, in the below screenshot, the second indentation bar shouldn't be drawn on the extended lines of line 511, 512, 514, 517, 522:

![indent-bars-wrong](https://github.com/jdtsmith/indent-bars/assets/193967/ac08c03a-22fa-48b8-bec2-bea11ef3df41)

Can you check if this is a bug and can it be fixed?

**Comment by taquangtrung** [comment]
FYI, a similar problem happens when a lot of indentation bars are displayed inside [lsp-ui-peek](https://github.com/emacs-lsp/lsp-ui?tab=readme-ov-file#lsp-ui-peek)

![lsp-peek-indent-bars](https://github.com/jdtsmith/indent-bars/assets/193967/d04019e3-f208-4dbb-aa32-04ca52760fe2)

**Comment by jdtsmith** [comment]
These seem different. What kind of  wrap is used in the first case.l? Visual or real?  Real wrap will certainly add new bars.  

In your daemon mode, that's strange. I've heard of some issues there but cannot test myself.  Can you report the value of face-remapping-alist and also do M-x describe-face indent-bars-1 and indent-bars-face?

**Comment by taquangtrung** [comment]
Thanks for your reply!

1. I'm using the customized `+word-wrap-mode` of Doom Emacs. It pushes all wrapped lines to have the same indentation as the first line that is being wrapped. They are all visual lines. You can see this in the below screenshot, the real line is highlighted in blue:

   ![indent-bars-visual-line](https://github.com/jdtsmith/indent-bars/assets/193967/4dec2387-91eb-4d0f-8491-a96ef0189e28)

2. Value of `face-remapping-alist` 

   ```elisp
   ((indent-bars-stipple
     (:stipple
      (9 19 "@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0@\0"))
     indent-bars-stipple))
   ```

3. The screenshot of `indent-bars` faces: they are the same in both the normal and daemon modes:

    ![indent-bars-faces](https://github.com/jdtsmith/indent-bars/assets/193967/786feb5e-d508-44dd-a5b5-203502144e4f)

**Comment by jdtsmith** [comment]
I don't know anything about Doom's word-wrap, but if it creates _real_ wrapping (actual charters in the buffer) bars will certainly (and correctly) be added.  

It looks like your `indent-bars--offset` is very small for some reason.  What value is it?  Is your 2nd language actually supported by indent-bars?  

I really can't understand the patterns you are getting at all.  Does it ever look correct?   Is this all only for `--daemon`? 

Can you go to some of the characters where bars look correct, and some where they look wrong, and `C-u C-x =` pasting the results?

**Comment by taquangtrung** [comment]
I discovered the reason, this is because I configured `(setq indent-bars-starting-column 0)`.  If I remove this setting, then the indent bars won't be drawn on the first char of each line. 

However, how can I still keep `(setq indent-bars-starting-column 0)` to make the indent like looks like VSCode?

**Comment by jdtsmith** [comment]
This is really not enough info to go on.  I don't ever see the patterns you have, so I cannot debug them.  Can you try this from emacs -Q, loading only indent bars and your prog mode and let me know if it remains?

**Comment by jdtsmith** [comment]
Thanks for digging into this, I've reproduced it.  Indeed `adaptive-wrap` is taking the face on the first character of the line and adding it to every character of its `wrap-prefix`:

```elisp
(defun adaptive-wrap--prefix-face (fcp _beg end)
  ;; If the fill-context-prefix already specifies a face, just use that.
  (cond ((get-text-property 0 'face fcp))
```

Unfortunately, I don't see a way to avoid this in `indent-bars` (other than not styling column 0, as is the default).  You could request upstream in `adaptive-wrap` (which I believe is being added to core and renamed `visual-wrap`) a changes to drop any faces found on whitespace from consideration.  

BTW, if you just want a smooth bar, `indent-bars-pattern="."` suffices.

**Comment by taquangtrung** [comment]
Thanks a lot for the analysis! 

Now I know where the issue's root cause is. At least I can manually hack `adaptive-wrap` for a temporary fix.
