### ISSUE TITLE
Bars not appearing

### ISSUE THREAD

**Issue by ahan98** [jdtsmith/indent-bars#4]
The bars don't appear for me at all.

<img width="278" alt="Screenshot 2023-07-30 at 3 14 27 PM" src="https://github.com/jdtsmith/indent-bars/assets/12192567/796ba9a8-6dd6-4ca1-9f72-47d2739b32a3">

I'm running [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) on MacOS 13.4.1. Output of `M-x emacs-version`:

```
GNU Emacs 29.0.91 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66))
```

Here's what I see when running `C-x C-e` on the provided [snippet](https://github.com/jdtsmith/indent-bars#stipples) to test stipples:

<img width="686" alt="Screenshot 2023-07-30 at 3 06 43 PM" src="https://github.com/jdtsmith/indent-bars/assets/12192567/9335f588-6810-49b8-b464-64dbd596085e">

I feel like the above screenshot shows that stipple isn't fully supported because the bars should appear on the buffer as well (not just the borders), right? Perhaps the package would work by switching to [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport), but I'm hoping that won't be necessary.

I don't think this issue is related to theme since the bars don't show even with all theming disabled. Just in case, I'm using the following theme:

```
(use-package ef-themes
  :init
  (setq ef-themes-mixed-fonts t)
  (setq ef-themes-headings
        '((0 . (variable-pitch light 1.9))
          (1 . (variable-pitch light 1.8))
          (2 . (variable-pitch regular 1.7))
          (3 . (variable-pitch regular 1.6))
          (4 . (variable-pitch regular 1.5))
          (5 . (variable-pitch 1.4))
          (6 . (variable-pitch 1.3))
          (7 . (variable-pitch 1.2))
          (t . (variable-pitch 1.1))))
  :config
  (load-theme 'ef-summer t))
```

I also don't think this is related to indentation, but here are the relevant indentation settings:

```
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
```

Below is some miscellaneous info on my setup.

In my `init.el`:

```
(use-package indent-bars
  :straight (:host github :repo "jdtsmith/indent-bars")
  :hook ((python-mode emacs-lisp-mode) . indent-bars-mode))
```

Output of `C-h v indent-bars-color-by-depth`: `(:regexp "outline-\\([0-9]+\\)" :blend 1)`

Screenshots of relevant faces from `M-x list-faces-display`:

<img width="1248" alt="Screenshot 2023-07-30 at 3 17 56 PM" src="https://github.com/jdtsmith/indent-bars/assets/12192567/b8eaf8e9-fc92-4e05-88e3-a478f2f7b7cc">

<img width="758" alt="Screenshot 2023-07-30 at 3 19 08 PM" src="https://github.com/jdtsmith/indent-bars/assets/12192567/33231694-779c-486a-a124-069aff2efba2">

**Comment by jdtsmith** [comment]
Please see [Compatibility](https://github.com/jdtsmith/indent-bars#compatibility).  It's interesting that _parts_ of the frame do stipple correctly. Here's a simplified test to try, in `*scratch*`:

```elisp
(let* ((w (window-font-width))
       (stipple `(,w 1 ,(apply #'unibyte-string
			       (append (make-list (1- (/ (+ w 7) 8)) ?\0)
				       '(1))))))
  (insert "\n" (propertize (concat  (make-string 15 ?\s)
				    "THIS IS A TEST"
				    (make-string 15 ?\s))
                           'face `(:background "red" :foreground "blue" :stipple ,stipple))))
```

**Comment by ahan98** [comment]
What is it supposed to look like? Here's what I see:

<img width="753" alt="Screenshot 2023-07-30 at 3 50 04 PM" src="https://github.com/jdtsmith/indent-bars/assets/12192567/26e3a910-3e82-481e-acc2-57129703a0d1">

**Comment by jdtsmith** [comment]
You are supposed to have bars.  Try `M-x font-lock-mode` to disable font lock and try again.

<img width="668" alt="image" src="https://github.com/jdtsmith/indent-bars/assets/93749/dd0f65f5-3cdc-4865-a66d-41365cecadd0">

On Mac I recommend emacs-mac (which I use).  It supports stipples perfectly.

**Comment by ahan98** [comment]
Ok, I'll try switching to emacs-mac then. Thanks.

**Comment by jdtsmith** [comment]
You might also open an issue with the maintainers of your port.  [Here is the patch](https://bitbucket.org/mituharu/emacs-mac/commits/25d1a744fc68eb8cd4e37443ac8ac3f7465f128e/raw) that enabled proper `:stipple` display on emacs-mac. Shouldn't be hard to get working everywhere.
