### ISSUE TITLE
Strange Behaviour of `(move-to-column)` function when using `indent-bars-display-on-blank-lines`

### ISSUE THREAD

**Issue by oxcl** [jdtsmith/indent-bars#40]
I came upon a problem with `ws-butler` package where after saving the file, if the cursor was at the beginning of an empty line, it jumped to the next line instead of staying on the same line. 
after investigating more i've realized the issue is that when `indent-bars-mode` is enabled with `indent-bars-display-on-blank-lines` set to `t`. the `(move-to-column)` function does not work correctly. 
when running `(move-to-column 100 t)` instead of the cursor going to the 100th character of the current line it jumps to the next line!

disabling `indent-bars-mode` or `indent-bars-display-on-blank-lines` fixes `(move-to-column)`
![2024-02-27-15-01-19](https://github.com/jdtsmith/indent-bars/assets/109025334/5bb10331-73fc-40e3-b773-da8a44ca6752)

**Comment by jdtsmith** [comment]
Evil user?  Did you [read this](https://github.com/jdtsmith/indent-bars#moving-by-columns)?

**Comment by oxcl** [comment]
no I'm not an evil user but i use `ws-butler` which also uses the move-to-column function.
i don't know if this is the smartest solution but i came up with this which works for me
```elisp
    (add-hook 'after-save-hook (lambda ()
                                 (when (and ws-butler-mode
                                            indent-bars-mode
                                            (string-match-p "\\`$" (thing-at-point 'line)))
                                   (indent-for-tab-command)
                                   (set-buffer-modified-p nil))))
```
thank you for the great package!

**Comment by oxcl** [comment]
a crazier solution would be this:
```elisp
    (add-hook 'before-save-hook (lambda ()
                                  (when (and indent-bars-mode (string-match-p "\\`\\s-*$" (thing-at-point 'line)))
                                    (indent-bars-mode -1)
                                    (setq oxcl/indent-bars-mode-off-for-now t))))
    (add-hook 'after-save-hook (lambda ()
                                 (when oxcl/indent-bars-mode-off-for-now
                                   (indent-bars-mode 1)
                                   (setq oxcl/indent-bars-mode-off-for-now nil))))
```

is it possible to temporarily disable indent bars only for the current line and enable it again after the save instead of disabling the whole mode?

**Comment by jdtsmith** [comment]
No it's all or nothing.  If you don't need blank line highlighting you could turn that off.

**Comment by jdtsmith** [comment]
It also looks like you could use `ws-butler-trim-predicate` to avoid attempting to trim empty lines altogether.

**Comment by oxcl** [comment]
ok. thanks for the quick response. i've settled with the disabling and enabling solution for now. it's not ideal but works good enough.
