### ISSUE TITLE
Plan to melpa?

### ISSUE THREAD

**Issue by falematte** [jdtsmith/indent-bars#41]

**Comment by jdtsmith** [comment]
Possibly ELPA.  I need to land/test the TS scope feature first.

**Comment by seagle0128** [comment]
Sorry to reply here. Just wanna know what's going on to releasing to ELPA.

**Comment by jdtsmith** [comment]
I'm about to merge the dev branch in, which uses a more efficient method for jit-lock.  Do you use the treesitter functionality, and if so, could you give it a test?

**Comment by seagle0128** [comment]
I am using tree-sitter. I'd like to help on testing. Please let me know how to test it. And I think it's better involve a few more volunteers.

**Comment by jdtsmith** [comment]
Just git clone this repo, enter the directory, `git checkout dev`, and configure treesitter support as [described in the README](https://github.com/jdtsmith/indent-bars/tree/dev#configuring-tree-sitter).  

Are you a python user?  If you use other languages with treesit, it would be useful to come up with some config for those (for `indent-bars-treesit-scope`).  Scope nodes are clearly "to taste", but for python I'm pretty happy with:

```elisp
(indent-bars-treesit-scope '((python function_definition class_definition for_statement
				       if_statement with_statement while_statement)))
```

**Comment by seagle0128** [comment]
@jdtsmith I tested for a few days, and seems working well for me. Only one note here, I am not using stipples, with Emacs 29.4 , on both Windows and macOS. My config is:

```elisp
(use-package indent-bars-ts
  :ensure nil
  :commands (indent-bars-ts-mode)
  :custom
  (indent-bars-treesit-support centaur-tree-sitter)
  (indent-bars-no-descend-string t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  (indent-bars-prefer-character t)
  (indent-bars-treesit-scope '((python function_definition class_definition for_statement
				                       if_statement with_statement while_statement)))
  :hook ((prog-mode yaml-mode) . indent-bars-mode)
  :config (require 'indent-bars-ts))
```

**Comment by jdtsmith** [comment]
Thanks. Is that because stipples aren't available for you?  Have you tried treesitter scope with any other languages besides python?

**Comment by seagle0128** [comment]
Right! I need to rebuild my Emacs to enable stipples. 

>Have you tried treesitter scope with any other languages besides python?

Yes. I've tried go, python,, sh and cpp files etc.

**Comment by jdtsmith** [comment]
Great. Do you want to mention your TS config in [the wiki](https://github.com/jdtsmith/indent-bars/wiki/indent%E2%80%90bars-config-Wiki)?

**Comment by seagle0128** [comment]
Np. 

BTW my Emacs config is [here](https://github.com/seagle0128/.emacs.d).
