### ISSUE TITLE
Using `syntax-ppss` for checking extra depth without tree-sitter?

### ISSUE THREAD

**Issue by alphapapa** [jdtsmith/indent-bars#42]
Hi JD,

I'm curious, have you considered using `syntax-ppss` to check whether a position is within a string or enclosed expression, without using tree-sitter?  e.g. somewhere around here, I guess:

https://github.com/jdtsmith/indent-bars/blob/4583e3e9f507143cd4241131b77fc5e8b1722bbf/indent-bars.el#L898-L900

That would allow not drawing extra bars for multi-line strings or parenthesized expressions, without having tree-sitter.  I use it in `prism-whitespace-mode`, and it works for Python, etc.

**Comment by jdtsmith** [comment]
This is certainly possible.  I have some new treesitter capability coming that allows you to focus on surrounding "scope", so this functionality was in a sense "free".   It also allows finer control, for example do not nest bars in calling sequences, but do inside of (nested) array/struct/list literals.  But the price for this is it requires a ts mode, a ts backend, and more config.  

Probably for strings at least I should allow a `ppss` fallback (e.g. if you just set it to `t`) for a TS-free option.

**Comment by jdtsmith** [comment]
v0.5 no includes `syntax-ppss` based string and list descent inhibiting by default, without the need for tree-sitter.  Give a test and see how it works for you.

**Comment by alphapapa** [comment]
This seems to work really well!  Thanks for your work on this.  It seems like the best package for this sort of thing in Emacs.  I think I'll be adding it to my config permanently.  :)

**Comment by jdtsmith** [comment]
Great to hear.  Let me know if you try out the TS capabilities.

**Comment by alphapapa** [comment]
I think my current Emacs installation doesn't support treesitter, and I haven't felt like I need it yet, so I haven't looked into it much.  Which TS capabilities do you think I should try?
