### ISSUE TITLE
Loading a modus theme with indent-bars loaded breaks font lock

### ISSUE THREAD

**Issue by fnurkla** [jdtsmith/indent-bars#43]
If I run `emacs -Q -l compat.el -l indent-bars.el` and then in Emacs do `M-x load-theme` selecting one of the modus themes, I get the messages `Error during redisplay: (jit-lock-function 1) signaled (void-function nil)` and then `funcall: Symbol’s function definition is void: nil` and font lock breaks for all buffers. 

This is with Emacs 30.0.5, but I also tried it with Emacs 29 when I tried to find what was causing the problem in my configuration, and that did not help.

**Comment by fnurkla** [comment]
Thank you for a quick response!

**Comment by jdtsmith** [comment]
v0.5 includes a new method more robust method for theme awareness.  Give a try and let me know of any issues.

**Comment by fnurkla** [comment]
From some cursory testing it seems so be working as intended.
