### ISSUE TITLE
`Debugger entered--Lisp error: (error "Selecting deleted buffer") ` from `(indent-bars--cleanup-stipple-remaps #<killed buffer>)`

### ISSUE THREAD

**Issue by hab25** [jdtsmith/indent-bars#44]
Unfortunately, not sure what the conditions to reproduce this are. 

I think it might have to do with `consult-recent-file` which makes temporary buffers that do run `prog-mode-hook` (from which I call `(indent-bars-mode)`). However, I was unable to consistently reproduce.

Nonetheless, it's probably trivially-implemented good practice (at least because it'll avoid similar issues) to just cancel this https://github.com/jdtsmith/indent-bars/blob/4974f6c16c7fcc8bbe53fbcd93c74794877287a1/indent-bars.el#L1394C5-L1396C79 timer on `kill-buffer-hook`, no?

Here's a backtrace (n.b. I use a few customizations to `backtrace`, the most notable being `(setopt backtrace-view '(:show-flags t :show-locals t))`; if it is unintelligible I can probably provide it uncustomized):

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")

(indent-bars--cleanup-stipple-remaps #<killed buffer>)

debugger-may-continue = t

inhibit-redisplay = nil

inhibit-debugger = t

inhibit-changing-match-data = nil

(apply indent-bars--cleanup-stipple-remaps #<killed buffer>)

[no locals]
(#[128 "\302\301\303\300\4\"\"\207"
       [(#<killed buffer>)
        indent-bars--cleanup-stipple-remaps
        apply
        append]
       6 "\n\n(fn &rest ARGS2)"])

[no locals]
(apply #[128 \302\301\303\300 "" \207
             [(#<killed buffer>)
              indent-bars--cleanup-stipple-remaps
              apply
              append]
             6

             (fn &rest ARGS2)]
       nil)

[no locals]
(timer-event-handler
 [t
  0 1 0 nil
  #[128 \302\301\303\300 "" \207
        [(#<killed buffer>)
         indent-bars--cleanup-stipple-remaps
         apply
         append]
        6

        (fn &rest ARGS2)]
  nil idle 0 nil])

inhibit-quit = t

```

**Comment by jdtsmith** [comment]
I pushed a small change to guard against this; please give it a test.

**Comment by jdtsmith** [comment]
Good catch, check 48c8f7e.
