### ISSUE TITLE
indent-bars face doesn't play well with whitespace-trailing face

### ISSUE THREAD

**Issue by DevelopmentCool2449** [jdtsmith/indent-bars#46]
When using whitespace-mode with indent-bars, the trailing whitespace face cuts off with indent-bars stipple face.
![bug](https://github.com/jdtsmith/indent-bars/assets/163072436/0b2c3821-e1e6-40d0-9704-a14bbe8b2ad4)

**Comment by jdtsmith** [comment]
I'm not understanding you, and am not familiar with `whitespace-mode`.  What did you expect to see here?  Is the red background on purpose?  indent-bars does not expect other modes to style the leading spaces there.  It applies `:foreground` and `:stipple` elements to `:face` (or `display` properties for tabs or "invented" spaces).

**Comment by jdtsmith** [comment]
I notice `whitespace-trailing` font-lock keyword specified `OVERRIDE`, so you just need it to appear later in the list of font-lock keywords, and it will override the face `indent-bars` places there.  So just turn on `whitespace-mode` after `indent-bars-mode`.

**Comment by DevelopmentCool2449** [comment]
> I notice `whitespace-trailing` font-lock keyword specified `OVERRIDE`, so you just need it to appear later in the list of font-lock keywords, and it will override the face `indent-bars` places there. So just turn on `whitespace-mode` after `indent-bars-mode`.

Thank you for the help, since i see it cannot be fixed i'm closing the issue.

**Comment by jdtsmith** [comment]
I did offer a potential fix:

> just turn on whitespace-mode after indent-bars-mode.

**Comment by DevelopmentCool2449** [comment]
I tried it but it doesn't work since it overrides the `indent-bars` `:stipple` face which makes it unusable.
![bug](https://github.com/jdtsmith/indent-bars/assets/163072436/47e7861d-66e3-4200-8ebc-234ec283deb4)

**Comment by jdtsmith** [comment]
Not so easy to solve, both tools want to control `face` on the leading spaces.
