### ISSUE TITLE
indent-bars-ts modifies a treesitter mode buffer upon being enabled/disabled.

### ISSUE THREAD

**Issue by khelmr** [jdtsmith/indent-bars#49]
Hi.

I'm experiencing a problem where whenever a treesitter mode is enabled, emacs thinks that the file has been modified when `indent-bars-treesit` support is set to `t` and `indent-bars-mode` is hooked to `prog-mode`. If the hook is removed, enabling `indent-bars-mode` interactively doesn't cause emacs to think the buffer has been modified, but disabling `indent-bars-mode` interactively causes emacs to think the buffer has been modified. This problem does not occur when using `indent-bars-mode` with non-treesitter modes.

Here's the relevant part of my config:
``` emacs-lisp
(use-package indent-bars
  :ensure (:host github :repo "jdtsmith/indent-bars")
  :hook (prog-mode . indent-bars-mode)
  :custom
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  (indent-bars-treesit-scope '((python function_definition class_definition for_statement
                                if_statement with_statement while_statement)))
  (indent-bars-color '(highlight :face-bg t :blend 0.2))
  (indent-bars-pattern ".")
  (indent-bars-width-frac 0.1)
  (indent-bars-pad-frac 0.1)
  (indent-bars-color-by-depth '(:regexp "outline-\\([0-9]+\\)" :blend 1))
  (indent-bars-highlight-current-depth '(:blend 0.5)))
```

Let me know if you need any additional information.

**Comment by jdtsmith** [comment]
Is this with the latest version?  I added a couple more protections to prevent unwanted buffer modification; can you update and let me know if that fixes it?

**Comment by khelmr** [comment]
Updated to the latest version. It partially resolves it. When the hook is present, emacs no longer reports a treesitter mode buffer as modified when `indent-bars-mode` is enabled. However, if I interactively disable `indent-bars-mode`, emacs will then detect the buffer as modified. This behavior also applies to non-treesitter mode buffers (not sure if this is new behavior; I only just now noticed).

**Comment by jdtsmith** [comment]
Good catch.  Try the latest and let me know if all the unwanted buffer modifications are resolved.

**Comment by khelmr** [comment]
That fixed it! Thanks for your help!
