### ISSUE TITLE
Does not work as expected with tab-based indent

### ISSUE THREAD

**Issue by zino23** [jdtsmith/indent-bars#5]
`Hardware`: MacBook Pro 16-inch, 2021 with Apple M1 Pro chip
`OS`: macOS Ventura 13.0.1 (22A400)
`Emacs`: 28.2 installed from `macos-mac` with `--with-native-compilation`
`indent-bars`: latest version

- Environment setup
Start emacs with `emacs-mac -Q`, load only `use-package`, and `indent-bars`, as is shown in the left window of the screenshot below.

- Problem
No guide bars are displayed. Yellow boxes mark the position where guide bars are expected.

![image](https://github.com/jdtsmith/indent-bars/assets/38125460/f2a1ff1a-229c-432c-aca0-af2ba08e6725)

If I add blank lines in between, unexpected guide bars are displayed.
![image](https://github.com/jdtsmith/indent-bars/assets/38125460/72137807-f59b-49fd-9489-a59be461c226)

I haven't got the time to look at the code. So far the package works great with `rust-mode` and `lua-mode`. Appreciate your work very much!

**Comment by jdtsmith** [comment]
That's strange.  Can you post the results of `M-x emacs-version`?  Also, what mode is this?  What does `C-h v c-basic-offset` say?

**Comment by zino23** [comment]
- `tab-width` is used to configure indentation offset. 
- `indent-tabs-mode` is not enabled

**Comment by jdtsmith** [comment]
Are you sure tabs aren't being inserted for indentation?  It seems perhaps they are.  If you go to the beginning of an indented line and press right-arrow, does it skip by 8 spaces?

**Comment by zino23** [comment]
Sorry, I can confirm `go-mode` enables `indent-tabs-mode` by default (which is because `gofmt` inserts tabs instead of spaces and does not provide an option to use spaces over the other). So at the moment, `go-mode` cannot take the advantage of `indent-bars` :(

**Comment by the42** [comment]
Just came here as I was excited about this package (as it also works in the terminal) just to see, that it can't handle tabs. I am also coding go. It's not so much go-mode inserting tabs (which it does) but gofmt enforcing tabs as indentation. I would say 95% of all go code is formatted according to these rules.

I wouldn't wonder if other programming languages or code beautifier are using tabs as indentation,

**Comment by jdtsmith** [comment]
Will see what I can do.

**Comment by jdtsmith** [comment]
OK, I've pushed to the `dev` branch a change that allows `indent-bars` to work with `indent-tabs-mode`, by applying a suitable `'display` property to the tab characters.  Note that `dev` also includes treesitter support and other new options, so if you have the ability to test this with your go files, please do.  If you encounter any issues, please let me know.

**Comment by the42** [comment]
I fetched last changes and did checkout the dev-branch
As I am on Windows I set  '(indent-bars-prefer-character t) 
However I do not see indent bars but on blank lines

**Comment by zino23** [comment]
I checked out the `dev` branch, when I enabled `indent-bars-mode`, the code is reformatted as shown in the gif. Seems like `tab-width` is changed in lines `indent-bars` should be displayed. I hope the gif can be of some help in illustrating the problems. 

![output](https://github.com/jdtsmith/indent-bars/assets/38125460/f3adf72e-7b6d-41b4-b879-d7c206bc15e4)


Thanks for you development!

**Comment by jdtsmith** [comment]
Thanks for testing.  That's what I get for trying this only in emacs-lisp-mode with indent-tabs-mode: there were corner case bugs for "single bars aligned on tab boundaries".  Please update dev and try again.   

Also, I guess there is a treesitter go mode builtin now?  Are people using that?  If you want to try it out, you could enable `indent-bars-treesit-support` and play around with `indent-bars-treesit-wrap` (after using treesit-explore-mode to find out the node types which wrap: usually function parameters and argument lists).

**Comment by jdtsmith** [comment]
You shouldn't disable `indent-tabs-mode`.  I understand that that mode is _required_ for go-mode.  When `indent-bars` sees `indent-tabs-mode`, it knows it has to handle tabs, and does so, whether with stipple or characters.

**Comment by the42** [comment]
That's it, looks good to me, thank you for your support and now works with tabs too.

**Comment by jdtsmith** [comment]
@zino23 any luck?

**Comment by zino23** [comment]
@jdtsmith It works like a charm in `go-mode` and `go-ts-mode` now! 

I haven't been able to get `indent-bars-treesit-wrap` to work though. As you can see in the picture, after I've set `indent-bars-treesit-wrap` with

```lisp
(setq indent-bars-treesit-wrap '((golang function_declaration if_statement block select_statement)))
```

I still got indent bars with depth more than 1 inside the wrapping elements. I've tested with `function_declaration`, `if_statement`, `block`, `select_statement`, all without success. 

![image](https://github.com/jdtsmith/indent-bars/assets/38125460/4b679031-95ac-4254-b7ef-7d0ab07badaa)

**Comment by jdtsmith** [comment]
Ok great.  I just made a few tweaks to how point is saved; please update dev again and give it a test.

The thing to do is `M-x treesit-explore-mode`, and select the beginning of the line where a wrap occurs, and you want it not to increase depth beyond the start.  But I don't quite understand the indentation here (not a Go user): your `var` is indented from `main`?  That doesn't look correct. 

In any case, you need to use the correct language name `go`, and will also need to turn off `no-descend-string` since the go string literal is named something weird (I don't know if go supports multi-line strings anyway).  

Here it is with `indent-bars-treesit-wrap = ((go if_statement))`.  

<img width="385" alt="image" src="https://github.com/jdtsmith/indent-bars/assets/93749/79124c8c-e9a3-4d79-b9de-df75199ea6c4">

Not sure you'd every want this, but you can see it works, and does not add more bars beneath the outermost `if`.
