### ISSUE TITLE
indent-bars doesn't handle unspecified background/foreground in face

### ISSUE THREAD

**Issue by brownts** [jdtsmith/indent-bars#50]
I had problems getting this mode to work and finally sat down to figure out the issue.  The problem manifests with the theme I'm using.  For `indent-bars` settings, I'm using just the default settings for the mode and add a `indent-bars-mode` to the `prog-mode-hook`.  The following is a backtrace of what I'm encountering.

```text
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  color-values(nil nil)
  color-name-to-rgb(nil)
  indent-bars--blend-colors(nil "#1e1e1e" 0.5)
  indent-bars--main-color(#s(indent-bars-style :tag nil :main-color nil :depth-palette nil :faces nil :stipple-face indent-bars-face :no-stipple-chars nil :current-stipple-face nil :current-bg-color nil :current-depth-palette nil))
  indent-bars--initialize-style(#s(indent-bars-style :tag nil :main-color nil :depth-palette nil :faces nil :stipple-face indent-bars-face :no-stipple-chars nil :current-stipple-face nil :current-bg-color nil :current-depth-palette nil))
  indent-bars-setup()
  indent-bars-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook lisp-data-mode-hook emacs-lisp-mode-hook lisp-interaction-mode-hook)
  apply(run-hooks change-major-mode-after-body-hook (prog-mode-hook lisp-data-mode-hook emacs-lisp-mode-hook lisp-interaction-mode-hook))
  run-mode-hooks(lisp-interaction-mode-hook)
  lisp-interaction-mode()
  command-line()
  normal-top-level()
```

What I discovered from above is that the face that was being used in my config (i.e., highlight) doesn't define a background (it's marked as "unspecified").  Once I made the following modification to `indent-bars--main-color` (to resolve through inherits back to the default face if necessary), I was finally able to see the stippled indent bars.

```diff
--- /home/troy/.emacs.custom/elpaca/repos/indent-bars/indent-bars.el
+++ #<buffer indent-bars.el>
@@ -570,7 +570,7 @@
   (cl-destructuring-bind (main &key face-bg blend) (indent-bars--style style "color")
     (let ((col (cond ((facep main)
 		      (funcall (if face-bg #'face-background #'face-foreground)
-			       main))
+			       main nil 'default))
 		     ((color-defined-p main) main)))
 	  (blend (or blend-override blend)))
       (if (and tint tint-blend (color-defined-p tint)) ;tint main color
```

Note that there are multiple places in the code where the use of `face-background` and `face-foreground` likely should be modified, this only a one place.

**Comment by jdtsmith** [comment]
Thanks for the report.  I don't think I've come across a `highlight` face with unspecified background, what theme is that?  I just uploaded a fix along the lines of this suggestion, being more defensive against unspecified face attributes in a few places.  Can you give it a quick test?

**Comment by brownts** [comment]
> Thanks for the report. I don't think I've come across a `highlight` face with unspecified background, what theme is that? 

[vscode-dark-plus-theme](https://github.com/ianyepan/vscode-dark-plus-emacs-theme)

> I just uploaded a fix along the lines of this suggestion, being more defensive against unspecified face attributes in a few places. Can you give it a quick test?

Yes, this works, thanks!
