### ISSUE TITLE
indent-bars-ts--update-indentation-depth called in non-treesitter modes

### ISSUE THREAD

**Issue by brownts** [jdtsmith/indent-bars#51]
I use a mix of tree-sitter and non-tree-sitter modes, so I've defined `indent-bars-treesit-support` to non-nil.  When a buffer is setup that supports tree-sitter, this causes `indent-bars-ts--setup` to be called which initializes `indent-bars--update-depth-function` to `indent-bars-ts--update-indentation-depth`.  Unfortunately, since `indent-bars--update-depth-function` is not buffer local, all modes (including non-tree-sitter modes) end up being directed to call `indent-bars-ts--update-indentation-depth` from  `indent-bars--current-indentation-depth`.  I believe the fix is to make the `indent-bars--update-depth-function` buffer local.  The following is a backtrace demonstrating this problem:

```text
Debugger entered--Lisp error: (treesit-no-parser #<buffer *Pp Macroexpand Output*>)
  treesit-buffer-root-node(nil)
  treesit-node-on(18 19 nil)
  indent-bars-ts--update-indentation-depth(0)
  indent-bars--current-indentation-depth(context)
  indent-bars--highlight-current-depth()
  indent-bars-setup()
  indent-bars-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook lisp-data-mode-hook emacs-lisp-mode-hook)
  apply(run-hooks change-major-mode-after-body-hook (prog-mode-hook lisp-data-mode-hook emacs-lisp-mode-hook))
  run-mode-hooks(emacs-lisp-mode-hook)
  emacs-lisp-mode()
  pp-display-expression(define-minor-mode "*Pp Macroexpand Output*" nil)
  pp-macroexpand-expression(define-minor-mode)
  pp-macroexpand-last-sexp(nil)
  funcall-interactively(pp-macroexpand-last-sexp nil)
  command-execute(pp-macroexpand-last-sexp record)
  execute-extended-command(nil "pp-macroexpand-last-sexp" #("pp" 0 2 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "pp-macroexpand-last-sexp" #("pp" 0 2 (ws-butler-chg chg)))
  command-execute(execute-extended-command)
```

Note, there might be some other variables that should be looked at as well to see if they should be buffer local (e.g., `indent-bars--ppss`, `indent-bars--teardown-functions`, etc).

**Comment by jdtsmith** [comment]
Thanks for the report.  Can you see if b63c46e fixes?

**Comment by brownts** [comment]
Yes, this fixes the issue, thanks!
