### ISSUE TITLE
Stopped working for me on MacOS

### ISSUE THREAD

**Issue by konrad1977** [jdtsmith/indent-bars#53]
I used the package prior to my vacation, like 8 weeks ago and then it worked. But now it stopped display lines. I am not using the stipple compliant version of Mac, so it should use character rendering instead. 

I wonder if there could be some other settings I applied that could interfere with Indent-bars?

I am using emacs-plus@29 with native compilation and xwidgets support

The config I am using.

```
(use-package indent-bars
  :hook (prog-mode . indent-bars-mode)
  :ensure nil
  :custom
  (indent-bars-color '(highlight :face-bg t :blend 0.1))
  (indent-bars-width-frac 0.3)
  (indent-bars-pad-frac 0.1)
  (indent-bars-zigzag nil)
  (indent-bars-pattern ".")
  (indent-bars-prefer-character t)
  (indent-bars-color-by-depth '(:regexp "outline-\\([0-9]+\\)" :blend 1)) ; blend=1: blend with BG only
  (indent-bars-highlight-current-depth '(:blend 0.5)) ; pump up the BG blend on current
  (indent-bars-display-on-blank-lines nil))
```

**Comment by jdtsmith** [comment]
Should work fine with `prefer-character=t`.  Maybe you are using a different major mode that indent-bars doesn't know about?  Try out e.g. python-ts-mode (or python-mode).  If it's still a problem, try loading from `emacs -Q` and provide a simple reproducer using only `indent-bars` and a builtt-in mode.

**Comment by konrad1977** [comment]
I am only using swift, and that worked 8 weeks ago. I'll check with the -Q flag.

**Comment by konrad1977** [comment]
After disabling tree-sitter-hl-mode it works.

**Comment by jdtsmith** [comment]
`tree-sitter` is an outdated mode providing treesitter support in Emacs, and was superseded by built-in support in Emacs 29+:

> For Emacs 29+, please use [the built-in integration](https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg01443.html) instead.

Not sure why it conflicts with indent-bars, but I'd recommend switching.

**Comment by konrad1977** [comment]
The parser I am using does not work with the built in version of treesit.

**Comment by jdtsmith** [comment]
Aha, that's surprising.  Which one is that?

**Comment by konrad1977** [comment]
I am using swift. And I am using this parser: 
https://gitlab.com/woolsweater/tree-sitter-swifter

I changed my config for tree-sitter to this:
`(use-package tree-sitter
  :hook (tree-sitter-after-on . tree-sitter-hl-mode)
  :config
  (global-tree-sitter-mode))

(use-package tree-sitter-langs
  :after tree-sitter)
`

From this:
```
(use-package tree-sitter
  :hook ((swift-mode . tree-sitter-mode))
  :config
  (setq tsc-dyn-get-from nil)
  (setq tree-sitter-hl-use-font-lock-keywords t
        tree-sitter-hl-enable-query-region-extension nil)
  :config
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))
```

And now everything works as expected.
