### ISSUE TITLE
Addressing stipple attribute issue on NS and PGTK systems

### ISSUE THREAD

**Issue by jamescherti** [jdtsmith/indent-bars#54]
The stipple attributes doesn't work on NS and PGTK, though it functions perfectly on Linux and GTK3. 

I’m wondering whether the `indent-bars` package should automatically behave as if `indent-bars-prefer-character` is set to `t` on NS and PGTK systems. This might help maintain the package's reputation for stability, as users might think it’s broken if they don’t see the bars. 

What do you think, @jdtsmith?

**Comment by jamescherti** [comment]
Let's hope this situation will be corrected soon.

(However, for NS or PGTK users with Emacs versions earlier than 30, `indent-bars` could automatically choose to use characters instead of stipple attributes.)

**Comment by jdtsmith** [comment]
I could include a warning message for these versions.  I don't want to hard-code it because sometimes people back-port changes.  Unfortunately Emacs pretends to fully support stipples in all GUI versions, and never indicates an error, so there's no reliable way to check for support.  

I'm also unclear about "Cairo".  Do you know, is that orthogonal/unrelated to PGTK vs. GTK?  I've had reports of stipple issues with Cairo as well; can you confirm this?

**Comment by jdtsmith** [comment]
Do you (or anyone else) have access to a PGTK machine?  What is `gtk-version-string` on it?

**Comment by jamescherti** [comment]
> I could include a warning message for these versions. I don't want to hard-code it because sometimes people back-port changes. Unfortunately Emacs pretends to fully support stipples in all GUI versions, and never indicates an error, so there's no reliable way to check for support (other than by hand).

That makes sense. A warning message could definitely help `indent-bars` users.

> I'm also unclear about "Cairo". Do you know, is that orthogonal/unrelated to PGTK vs. GTK? I've had reports of stipple issues with Cairo as well; can you confirm this?

I am using Emacs (versions 29.4 and 30) compiled with `--with-x-toolkit=gtk3` and Cairo (as verified by `(featurep 'cairo)` returning `t`). In this setup, `indent-bars` works flawlessly.

(I also compiled Emacs 29.4 with `--with-cairo-xcb` on Linux/GTK3, and `indent-bars` still displays the bars correctly.)

**Comment by jamescherti** [comment]
For some reason, when I tried `indent-bars` on another Debian Bookworm Linux computer with the same Debian version, same Emacs version, and same compile flags, the stipple attributes didn't work. It's odd.

**Comment by jdtsmith** [comment]
For real?  That's maddening, but there must be _some_ difference.  Did you also try the simple Stipple test in the README to be sure it wasn't some configuration issue?  I haven't had a lot of takers in actually testing across all the various systems, so I'm shooting in the dark.  It's super helpful to have this info. 

@minad: sounds like Cairo maybe isn't the culprit.

**Comment by jamescherti** [comment]
This is how it looks in the Debian computer where `indent-bars` does not work:
![image](https://github.com/user-attachments/assets/cb11b95f-a630-4da7-bc6b-fe449c024601)

(even the init files, loaded packages are the same. It is a replica.)

**Comment by jdtsmith** [comment]
So strange. The GTK and Cairo versions are _exactly_ the same?  How about font (just guessing here)?

**Comment by jamescherti** [comment]
GTK and Cairo versions are identical (3.24.38 and 1.16.0, respectively). The Linux distribution is the same, the window manager is the same, and the font is also the same:
```
(set-frame-font "Iosevka Term Semibold-12" nil t)
```

The only difference is the speed (number of CPUs, RAM, etc.). It doesn't work on the older machine, but it works on the newer one.

**Comment by jdtsmith** [comment]
Monitor dpi?

**Comment by jamescherti** [comment]
The monitor's DPI could be the issue, as it's the main difference between the two computers. Stipples may depend on the display's pixel density to render properly. Have you ever discussed this with the Emacs developers?

Here’s a quick fix that users can add to their configuration to ensure indent-bars always work:
```emacs-lisp
(setq indent-bars-prefer-character (when (and (eq initial-window-system 'pgtk)
                                              (eq window-system 'ns))
                                     t)) 
```

**Comment by jdtsmith** [comment]
I'd prefer not to hard-code `indent-bars-prefer-character`, but rather find and fix the issue.  What is `(window-font-width)` on each system?  Play around with the stipple value in the test above and see if you can see anything?  If we can understand the real issue maybe we can fix it.

**Comment by jamescherti** [comment]
In both systems, `(window-font-width)` return "9".

**Comment by jdtsmith** [comment]
> In both systems, `(window-font-width)` return "9".

Strange, the high-dpi is often larger. Can you change the stipple list to 5 1's and 4 0's above?

**Comment by jamescherti** [comment]
Please provide the exact test Elisp code so we can ensure the result matches the specified code.

**Comment by jdtsmith** [comment]
Try this:

```elisp
(let* ((w (window-font-width))
       (stipple `(,w 1 ,(apply #'unibyte-string (make-list (/ (+ w 7) 8) 186)))))
  (insert "\n" (propertize (concat  (make-string 15 ?\s)
				    "THIS IS A TEST"
				    (make-string 15 ?\s))
                           'face `(:background "red" :foreground "blue" :stipple ,stipple))))
```

Should look like:

<img width="344" alt="image" src="https://github.com/user-attachments/assets/071793da-6051-4dc9-b990-aeb27700dcb6">

**Comment by jamescherti** [comment]
Tested using:
![image](https://github.com/user-attachments/assets/5d99274c-02ef-4848-969f-3bfad64c2a79)

Result:
![image](https://github.com/user-attachments/assets/1ede8919-004b-4237-bcd5-70a23a50b50e)

**Comment by jdtsmith** [comment]
OK thanks.  So that's pretty definitive.  Two things to try if you can:

- change the DPI to see if stipples return.
- try a non-Cairo version at high-DPI.

**Comment by jdtsmith** [comment]
Well that's even stranger then.  Yes, `--without-cairo` is good to try; unfortunately I'm not an expert on Linux build flags.  Is `system-configuration-features` identical on both systems?   There must be something different about these two systems!

**Comment by jamescherti** [comment]
I compared the `features` variable on both machines, and it is identical.

I will proceed with testing using `--without-cairo` and will keep you updated.

**Comment by jamescherti** [comment]
Compiling with the `--without-cairo` flag worked. However, this doesn't explain why it worked on the other computer with `--with-cairo`.

**Comment by jdtsmith** [comment]
Interesting, so Cairo is implicated after all, right?  I'm not familiar with Cairo unfortunately.  Would you be able to open a bug report (by sending an email to bug-gnu-emacs@gnu.org)?

**Comment by jdtsmith** [comment]
The report wouldn't be about `indent-bars`, just the stipple test above.  To get traction on the issue, it would be preferable if you submitted, and I can chime in with any details (i.e. just post the bug number here).  You always imagine a team of Emacs developers pouncing on bugs and testing across a build-farm of Emacs hosts, but they are severely understaffed in this department.  You're lucky to get the attention of one, and if they don't have the right system setup to reproduce it, or someone to test potential fixes, the bug just gets ignored.

Alternatively I can submit it and copy you, if you are able and willing to install test patches they propose.

**Comment by jamescherti** [comment]
Yes, please submit it and include me in the communication. I’d be happy to test the patches on the computer where the stipple attribute isn’t working.

**Comment by jdtsmith** [comment]
Great thanks.  Check your Reddit PM for a req RE email.

**Comment by jdtsmith** [comment]
I haven't been able to connect with you to get an email.  The [bug report is filed](https://yhetil.org/emacs-bugs/m2mskk7zpa.fsf@macmutant.fritz.box/T/#t), and it would be useful if you could copy yourself into the conversation.  I find the easiest way to do that is download MBOX, and import it into my mail client, then reply-all from there.  Po Lu is surprised about Cairo being an issue, since the capability is shared with PGTK.  

BTW, did you compile Emacs v30 on both of your Cairo systems?

**Comment by jamescherti** [comment]
> BTW, did you compile Emacs v30 on both of your Cairo systems?

Yes

It is working in one of them Cairo systems:
![image](https://github.com/user-attachments/assets/948964b9-2030-43b0-a168-0282a146d8a5)

But not in the other that is exactly the same.

Both of them are the same Linux distribution, same Emacs version (30.0.9) and compile flags.

**Comment by jdtsmith** [comment]
Thanks.  I ask because your earlier version screenshot mentions v29.4.  Let's see if Po has any ideas.

**Comment by jamescherti** [comment]
Yes, I tested it across multiple versions (29.4, 30, 31) and observed the same outcome.

**Comment by jdtsmith** [comment]
Truly mysterious. Must be some other Cairo setting then.  Are there any other config settings for display that differ between the systems?  I know we've ruled out high-DPI.

**Comment by jamescherti** [comment]
I programmatically configure my computers using Ansible and scripts, which replicate the same configuration across multiple machines. The configurations are generally uniform.

What specific display configuration settings are you referring to, JD?

**Comment by jdtsmith** [comment]
I see.  I'm not a desktop Linux user so I can't really say; just fishing in the dark here.  I suspect the bug discussion will generate these same type of questions ("so what's different?").  Sounds like you have compiled multiple identical Emacs versions on two identical systems, and gotten different stipple results (always good on system 1, only good on system 2 `--without-cairo`).  That might indicate there are some as yet _hidden variables_: e.g. system settings (Cairo settings?) which are not expressed in the emacs build flags that could differ between 1 & 2.  Or some other non-gremlin logical reason :).
