### ISSUE TITLE
Possible to highlight only the current scope, ts or otherwise?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [jdtsmith/indent-bars#55]
Looking through the examples it's possible to highlight the current depth, but is it possible to only highlight the current scope?

**Comment by jdtsmith** [comment]
Scope is a treesit feature.  If you don't want to see anything "out of scope", my recommendation would be to change the `:blend` factor in `indent-bars-ts-color` to 0.01 or lower.  `M-x customize-group indent-bars-ts-style` is the easiest to try for that.

**Comment by JordanAnthonyKing** [comment]
> Scope is a treesit feature. If you don't want to see any bars which are "out of scope", my recommendation would be to change the `:blend` factor in `indent-bars-ts-color` to 0.01 or lower. `M-x customize-group indent-bars-ts-style` is the easiest to try for that.
> 
> Also, I don't yet have examples for scope-based styling, so if you get something you're happy with, please post and I'll add to the examples page.

Sure, let me get back to you.

**Comment by JordanAnthonyKing** [comment]
@jdtsmith maybe I'm a bit slow but I keep running into the inverse of what I want:

![image](https://github.com/user-attachments/assets/0fd22aaa-a550-4a59-a81c-d62845398f70)

```
  (setq indent-bars-color-by-depth nil
        indent-bars-color '(highlight :face-bg t :blend 0.01)
        indent-bars-highlight-current-depth '(:blend 0.01)
        indent-bars-ts-color '(highlight :face-bg t :blend 0.01)
        indent-bars-ts-highlight-current-depth '(no-inherit :blend 1.0))
```

**Comment by jdtsmith** [comment]
Of the 4 style targets (in-scope, out-of-scope=ts) x (normal, current-depth), you've set 3 of them to be nearly invisible, leaving only out-of-scope current-depth bars visible.  So that's what you're getting.  You probably don't want this, as in non-TS modes you'll see... nothing.  

I'm not sure what the inverse of this would be — everything except o-o-s current-depth visible? 

Maybe you're looking for something like:

```elisp
(setopt indent-bars-color '(highlight :face-bg t :blend 0.75) ; in-scope
        indent-bars-highlight-current-depth '(:pattern ".")   ; in-scope current
        indent-bars-color-by-depth nil
        indent-bars-ts-color '(highlight :blend 0.01) ; out of scope = invisible
        indent-bars-ts-highlight-current-depth nil)   ; no current depth oos
```

**Comment by JordanAnthonyKing** [comment]
Not quite what I was looking for but I kinda dig it:

![image](https://github.com/user-attachments/assets/36ebb879-ddd7-44d8-9daa-f8b9eb39b18e)

![image](https://github.com/user-attachments/assets/f59984a5-1bc7-4f5c-96fd-0a50fd1f1d66)

Ideally I wouldn't want the inner scopes highlighting but maybe I actually prefer this.

**Comment by jdtsmith** [comment]
It's quite unclear what you want.  If you don't want in-scope current-depth highlight, set `indent-bars-highlight-current-depth=nil`.   What's going on above is point is on a line starting "if" and the current depth of that line is being highlighted within its scope, just as you have configured.  If you had point on the "f" of "if", the current scope would likely be smaller (just the short if block).
