### ISSUE TITLE
Strange behaviour (spaces show stipples, tabulators don't)

### ISSUE THREAD

**Issue by paaguti** [jdtsmith/indent-bars#58]
Latest indent-bars (after PR#57) on a bash script:

![image](https://github.com/user-attachments/assets/4bb28930-3288-4263-8c88-dd801b2b1096)

On line 9, I have tabulators (chr(9)) instead of whitespaces (chr(32))

GNU Emacs 30.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33,
 cairo version 1.16.0) of 2024-09-15

**Comment by jdtsmith** [comment]
Is this new behavior?  What is the value of `indent-tabs-mode' in the buffer?   If you are indenting with tabs, it needs to be `t'.

**Comment by jdtsmith** [comment]
Assuming this answer it.
