### ISSUE TITLE
indent-bars not on GNU ELPA

### ISSUE THREAD

**Issue by the42** [jdtsmith/indent-bars#59]
According to the readme (and the emacs development mailing list) indent-bars should be on GNU ELPA, alas it isn't:

![grafik](https://github.com/user-attachments/assets/b1496c6e-9952-4c93-9d55-fde6d2a8774d)

(If I am just to impatient, my apologies)

**Comment by jdtsmith** [comment]
Just went in yesterday.  We had a glitch in the ELPA build process, so hopefully it will show up today.

**Comment by jdtsmith** [comment]
Should be available now.
