### ISSUE TITLE
indent-bars-mode toggle leaves indent-bars-ts-mode enabled when it should not

### ISSUE THREAD

**Issue by shipmints** [jdtsmith/indent-bars#60]
Via C-h m after loading a python buffer with indent-bars-mode enabled via a prog-mode-hook:

```Minor modes enabled in this buffer: Breadcrumb-Local Corfu Diff-Hl
Display-Line-Numbers Eldoc Flymake Font-Lock Indent-Bars
Indent-Bars-Ts Jinx Prism-Whitespace Pulsar Rainbow
Ruff-Format-On-Save Show-Paren-Local Subword Yafolding

The major mode is Python-ts mode defined in python.el:
```

Then after typing M-x indent-bars-mode:

```Minor modes enabled in this buffer: Breadcrumb-Local Corfu Diff-Hl
Display-Line-Numbers Eldoc Flymake Font-Lock Indent-Bars-Ts Jinx
Prism-Whitespace Pulsar Rainbow Ruff-Format-On-Save Show-Paren-Local
Subword Yafolding

The major mode is Python-ts mode defined in python.el:
```

**Comment by jdtsmith** [comment]
Good catch.  It was being disable in all but name. Fixed in 6dc2955; give a try.

**Comment by shipmints** [comment]
Using master...not working. This could be related to #61 not sure. There's nothing in *Messages*. I will disable prism entirely and see.

With indent-bars on by default via hook:

```Minor modes enabled in this buffer: Aggressive-Indent Breadcrumb-Local
Corfu Diff-Hl Display-Line-Numbers Eldoc Electric-Indent-Local Flymake
Font-Lock Highlight-Function-Calls Indent-Bars--Ts Indent-Bars Jinx
Page-Break-Lines Prism Pulsar Rainbow Show-Paren-Local Subword
Yafolding
```
After manually toggling:

```Minor modes enabled in this buffer: Aggressive-Indent Breadcrumb-Local
Corfu Diff-Hl Display-Line-Numbers Eldoc Electric-Indent-Local Flymake
Font-Lock Highlight-Function-Calls Indent-Bars--Ts Jinx
Page-Break-Lines Prism Pulsar Rainbow Show-Paren-Local Subword
Yafolding
```

**Comment by jdtsmith** [comment]
Ahh, stupid idea.  Try master again.

**Comment by jdtsmith** [comment]
What is the value of `indent-bars--ts-mode` after you disable?

**Comment by jdtsmith** [comment]
```elisp
funcall-interactively(indent-bars--ts-mode toggle)
```

Did you try to disable the mode yourself?  That was the problem (but should be avoided now).

**Comment by shipmints** [comment]
Yeah, I was experimenting to see if I could track down what it's doing without resorting to debugging it directly.

**Comment by shipmints** [comment]
You'd think that if it was already torn down, that disabling by hand would be a no-op.

**Comment by jdtsmith** [comment]
Is master working for you now?

**Comment by shipmints** [comment]
Just pulled and restarted. Both this and #61 seem resolved. I deleted the other highlighting indenters so am committed to IBM now. I'll keep using it and report back if other things crop up.
