### ISSUE TITLE
indent-bars-mode conflicting with prism-whitespace-mode

### ISSUE THREAD

**Issue by shipmints** [jdtsmith/indent-bars#61]
I haven't done an analysis to see what it's stuck doing but it shouldn't take 15 seconds to disable it for a single buffer. I will try to reproduce in emacs -Q. For what it's worth, indent-bars-mode on MacOS without stipple support and char-mode enabled, works in elisp buffers but not in python buffers. Perhaps whatever is interfering with it is what is causing the issue. No backtrace or any clues.

**Comment by shipmints** [comment]
If I disable prism-whitespace-mode, indent-bars works and disabling is faster. There's some negative interaction between these packages. I don't know if Adam @alphapapa is using both modes (yet!) but it is worth looking into. prism and indent-bars work fine together in elisp buffers.

**Comment by jdtsmith** [comment]
It should be instantaneous to enable/disable.  Is emacs responsive during this 15s?  Is this happening even without treesit?  Certainly should work in Python buffers; that's where I use it most.  

Check `Messages` to see if there are any vague font-lock errors reported when you have prism on?  I'm not sure how/why prism would interfere with indent-bars, since it appears to style text only (parens, blocks, etc.), and this mode only styles spaces and tabs at the beginning of lines.   Now, if it overwrites `'face` or `display` over full blocks of text in a jit-lock function of its own, and comes _later_ than indent-bars, it will overwrite the bars.  For fixing that, it might work to enable `indent-bars` last in your mode hook.  The same thing happens with e.g. Python multi-line strings, but `indent-bars` runs after font-lock when needed, and so overcomes that.

**Comment by jdtsmith** [comment]
What was the error?  This seems to happening in prism code.  

If you just `M-: (font-lock-ensure)` in a buffer with prism-mode enabled (leaving indent-bars out of it), does that cause a similar error/slowdown?

**Comment by shipmints** [comment]
Font lock is broken with the file I was trying to edit. I guess I should report this to the bug list. The "That:" in the multi-line comment screws it up. I haven't tried without treesit. I'll do that now. This could be the cause of some issues. What do you think?

```python
#!/usr/bin/env python

def foo:
    pass

class bar:
    def func:
        """
        This: is a comment.
        That: is a comment.
        """
        if True:
            pass

def baz:
    if True:
        if True:
            if True:
                print('True')
```

<img width="359" alt="image" src="https://github.com/user-attachments/assets/b1678a62-7928-46a4-8c6a-02a4b0a306f7">

**Comment by shipmints** [comment]
I updated my grammars. Will monitor. It surprises me (I'm new-ish to treesitter) that any program that python3 can run is not considered acceptable and that the grammar writers/font-lock writers have an opinion about what well-formed programs might be that differs from the compiler/interpreter platform itself.

I also can't understand why they don't build version numbers into the grammars to interrogate along with compiler traces. How the heck do they enjoy supporting the ecosystem. I feel for Joao, too, the LSP world seems the same.

**Comment by jdtsmith** [comment]
If you haven't updated python-mode.el in a while, you might.  Its sexp navigation was hanging on partially open multi-line strings.   If font-lock hangs up it might be the cause.   This file works fine for me in `python-ts-mode`:

<img width="254" alt="image" src="https://github.com/user-attachments/assets/3e5f15c3-2824-4c87-931d-6db63d4131b4">

Not sure why treesitter grammars are not versioned, but it's a pain.

**Comment by alphapapa** [comment]
FWIW, I use `prism-whitespace-mode` with Python buffers (not using Tree-Sitter), and it works fine.  Also, I've been using `prism-whitespace-mode` with `indent-bars-mode` in a large YAML buffer, and it works fine.

**Comment by jdtsmith** [comment]
@shipmints I think if a bug or package incompatibility remains here you need to put some work into isolating it, starting with `emacs -Q`.   Let me know.

**Comment by jdtsmith** [comment]
Other reports indicate there is no conflict between the 2 packages, so this must be an issue specific to your config.  Can re-open if not.

**Comment by shipmints** [comment]
> If you haven't updated python-mode.el in a while, you might. Its sexp navigation was hanging on partially open multi-line strings. If font-lock hangs up it might be the cause. This file works fine for me in `python-ts-mode`:

I'm still on 29.3 and the most recent python.el needs lots of changes from subr.el and that's a hassle to hack. Is there a reasonably recent commit for python.el that you know works that I can nab from the emacs-mirror?

**Comment by jdtsmith** [comment]
I'm using python.el ;; Version: 0.28.  BTW, there's a screenshot of prism-ws-mode and indent-bars working together in the examples file.

**Comment by shipmints** [comment]
Thanks for that. Emacs 29.3 ships with 0.28. Struggling with pretty severe performance issues, surely self inflicted via configuration, but hard to tease apart. Profiling is of limited use, pointing to the cost of line-move-visual just moving line by line, and disabling prism or indent-bars speeds things up and disabling both even more. I wonder if it's something like the font I'm using on this NS Mac build, Inconsolata. Perhaps I'll try a built-in font and see if that speeds up the display engine. Performance seems acceptable on tty. Hrumph.

**Comment by jdtsmith** [comment]
I guess you use evil?  Try without that.

**Comment by shipmints** [comment]
I'm an Emacs die-hard no evil here, though I am ambidextrous and can use vi.

I will spend the day disabling every minor mode and bisecting WTF is going on.

I switched to Menlo, Apple's built-in fixed-width font and no improvements there. I also disabled font smoothing and nothing there, either. This is all in Emacs (and my own choices), it seems.

**Comment by shipmints** [comment]
Okay I bisected down to indent-bars. With font-lock disabled it causes `line-move` to be very slow. This is in an emacs-lisp buffer with no treesit grammars enabled (I disabled treesit globally). Yet indent-bars--ts is still enabled. Could that be a culprit?

**Comment by jdtsmith** [comment]
So `indent-bars` _alone_ causes this for you in emacs-lisp mode?  If font-lock is disabled, `indent-bars` should do nothing.  TS is irrelevant there.  

I don't see any such slowdowns.  Since `emacs-lisp-mode` is builtin, you should be able to load only `indent-bars` starting from emacs -Q and test.  

For the error you wrote about, this looks like a problematic file structure and syntactic scan having problems, i.e. nothing to do with indent-bars.  `jit-lock` arranges to invalidate syntax scanning if `jit-lock-contextually` is non-nil.

As a test on speed, try this in the buffer: 

1. Leave `indent-bars` off.
2. `M-: (benchmark-run 1 (font-lock-ensure))`
3. Try again with `indent-bars` on.

For me, it's a bit slower when indent-bars is on, but both are less than 200ms.  Normally you'd never re-fontify the entire buffer. 

I altered the way I refontify on teardown; try out the latest and let me know if that makes a difference.

**Comment by shipmints** [comment]
With prism-mode on,  indent-bars-mode off: 12.8 seconds.
With prism-mode on,  indent-bars-mode on : 14.5 seconds.
With prism-mode off, indent-bars-mode-off:  1.3 seconds.
With prism-mode off, indent-bars-mode on :  2.1 seconds.

Nothing special about 69925. Just a "big" function with a bunch going on.

The change you made to teardown is much faster.

**Comment by shipmints** [comment]
Running the font-lock benchmark on prism.el itself after flushing takes 5 seconds with prism mode enabled and 0.8 seconds with prism off. I picked a file we both have access to to test on.

**Comment by shipmints** [comment]
Lemme try disabling depth detection. I have testing -Q and benchmarking font-lock-ensure after flush on prism.el is 6 seconds Emacs 29.3, iMac 16 cores, 128GB RAM.

**Comment by shipmints** [comment]
Disabling depth has no benefit that I can tell. Plus, I'd been using a 0.3 delay so would not be impacted "real time."

**Comment by jdtsmith** [comment]
Can you double check that `post-command-hook` does not mention indent-bars?  If it does, looking at the code, you _may_ need to also disable `indent-bars-ts-highlight-current-depth` and reset.

**Comment by shipmints** [comment]
Yep post-command-hook does have indent-bars--highlight-current-depth. I'll just restart my session and check again. Typo maybe? ```indent-bars-ts-highlight-current-depth``` does not exist.

**Comment by jdtsmith** [comment]
And one other thing: can you turn off character-only-mode (even if this means bars don't display correctly) and see if that changes line-move performance.  And just to be sure, can you create a short elisp section that can be run from emacs -Q that (for you) exhibits slow line-move in prism.el?

**Comment by shipmints** [comment]
No impact from stipple mode (other than I can't see them). Same line-move issue. Lemme take a look at extracting something from prism.el.

**Comment by jdtsmith** [comment]
Sorry I meant create an elisp recipe to run from `emacs -Q` which enables indent-bars with your settings, confirm is shows a slow line-move in prism.el, and that way we can be sure we're trying the same thing?

**Comment by shipmints** [comment]
```$ emacs -Q -l indent-bars-repro.el```
Then load indent-bars-repro.el itself and move up and down.
(The top part are just innocuous creature comforts for me/us to test.)
When you get to prism-match, line-move is much slower.

Farging github won't let me attach an ".el" file so I had to call it ".el.txt"...

[indent-bars-repro.el.txt](https://github.com/user-attachments/files/17168232/indent-bars-repro.el.txt)

**Comment by jdtsmith** [comment]
Thanks.  Usually what's needed to make progress in this scenario is a _minimal_ reproducer, i.e. no prism, just indent-bars (and whatever indent-bars settings are giving you `line-move` trouble).  Like this:

```elisp
(package-activate-all)

(setq ns-alternate-modifier       'meta) ; option
(setq ns-command-modifier         'meta) ; command
(setq ns-control-modifier         'control) ; control
(setq ns-right-alternate-modifier 'super) ; option
(setq ns-right-command-modifier   'hyper) ; command
(setq ns-right-control-modifier   'left) ; Note: Macbook keyboards do not have right-hand control keys
(setq ns-function-modifier        'hyper) ; Function (fn) key; default 'none
(when (display-graphic-p)
  (setq window-resize-pixelwise t)
  (setq frame-inhibit-implied-resize t)
  (setq frame-resize-pixelwise t))

(require 'indent-bars)
(setq indent-bars-highlight-current-depth nil)
(setq indent-bars-treesit-support nil)
(add-hook 'emacs-lisp-mode-hook #'indent-bars-mode)
```

Does that still show slowness for you with `emacs -Q`?  For me line-move is taking 3ms from the start of prism.el:

```elisp
(benchmark-run 1000 (line-move 1)) ; (3.3529649999999998 11 0.2837089999999999)
```

BTW, your syntax-table modifications may have something to do with slow font-lock.

**Comment by shipmints** [comment]
Now I sound like a n00b... Where would I see syntax-table modifications? There may be some but they're implied, not explicit.

I'll do more testing tomorrow morning. Off to Oktoberfest. Prosit!

**Comment by jdtsmith** [comment]
> Now, it's no prism, indent-bars, no current depth, line-move still a snail.****

I interpreted that to mean prism isn't required for slow line-move....

**Comment by shipmints** [comment]
> > Now, it's no prism, indent-bars, no current depth, line-move still a snail.****
> 
> I interpreted that to mean prism isn't required for slow line-move....

Correct. Just using prism's highly indented prism-match function as a sample we both can experiment with.

**Comment by jdtsmith** [comment]
OK I see.  5s total for all 1000 `line-move`s?  That's not _too_ bad compared to mine (5ms each vs. 3ms), and likely with the range of machine performance.   That should not be noticeable.    So I'm not sure how 5ms or even 10ms line-move is "a snail", unless you like to visit >200 lines in 1 second somehow :).  A very fast key repeat rate is 15ms; typical is 30ms.

**Comment by shipmints** [comment]
It's borderline unusable, though. Just up and down takes a whole second in sections of code. Moving right and left. Typing new code. All painful. I'm happy for it to be my config but I don't know where else to look. Syntax tables, you say?

**Comment by jdtsmith** [comment]
There's an inconsistency here — 5s for 1000 moves really doesn't jive with "up and down takes a whole second".   That would mean it would take you ~1000s to move 1000 lines.  

Is that really true?  17min(!) to navigate down 1000 lines by hand?   If so, is that true **with the simple reproducer above** from `emacs -q`?

I'm afraid we're kind of spinning in circles here.  There's no reason I know of that indent-bars should affect left/right moves; without current depth highlighting, literally _no_ indent-bars code of any kind is called during those.  Even with current-depth-highlighting, this is protected by a timer, and is very fast to run (~100µs!).  So nothing in indent-bars should be causing this.

I suspect other things in your font-lock system are problematic (the syntactic parsing errors you saw may be involved, but if you are using the simple reproducer above that can't be it).  The fact that prism is so slow for you too might indicate something wrong with your emacs build.

**Comment by shipmints** [comment]
Been spelunking through the code trying to figure this out with my configuration. When I comment out ```put-text-property``` in ```indent-bars--draw-line```, it's kinda almost normal performance. I still don't know why.

```elisp
(defun indent-bars--draw-line (style nbars start end &optional
				     invent switch-after style2)
...
	      ;; (put-text-property
	      ;;  pos (1+ pos)
              ;;  prop (funcall fun
	      ;;                (cond ((integerp switch-after)
	      ;;                       (prog1
	      ;;   	                (if (> switch-after 0) style style2)
	      ;;   	              (cl-decf switch-after)
	      ;;   	              (when (<= switch-after 0)
	      ;;   	                (setq switch-after t))))
	      ;;                      ((eq switch-after t) style2)
	      ;;                      (t style))
	      ;;                bar))
...
```

I also moved these invariants to the top, out of the loop, not that it's anything but hygeinic:

```elisp
      (let* ((tabs (and indent-tabs-mode
		        (save-excursion
		          (goto-char start) (looking-at "^\t+"))
		        (- (match-end 0) (match-beginning 0))))
	     (vp indent-bars--offset)
	     (style (or style indent-bars-style))
	     (bar 1) prop fun tnum bars-drawn)
        ;; these are invariant, right?
        (if indent-bars--no-stipple
	    (setq prop 'indent-bars-display fun #'indent-bars--no-stipple-char)
	  (setq prop 'face fun #'indent-bars--face))
```

**Comment by jdtsmith** [comment]
Undo all that and `M-x trace-function indent-bars--draw-line`.  This function should _not_ be called just moving point around with the arrow keys.  So this commenting out should do nothing.  When you scroll down, you _should_ see calls to this function, as font-lock notices unfontified text and asks to fontify.

**Comment by shipmints** [comment]
Gets called exactly as you expect. I'm not saying that the issue is with indent-bars--draw line but why these specific properties are causing me trouble. Do the degree other people will have similar issues, I'm trying to figure it out for me and them. This is an area of Emacs behavior I've not looked into before so trying to debug it is black magic until my mental model forms. Looking for ideas, if you have any.

**Comment by jdtsmith** [comment]
You mean it _doesn't_ get called as I expect?  What you've done is I think basically removed the drawing of the bars.  So it does seem that for whatever reason your emacs is highly sensitive to extra font-lock info in the buffer.  I don't know why.  I mean indent-bars roughly doubles the number of text ranges with distinct font-lock properties.  But your performance sounds like it's getting >10x worse.  

Move around various places and `C-u C-x =` to see if the properties being applied make sense.  On bars, you should see stuff like:

```
There are text properties here:
  face                 indent-bars-2
  fontified            t
```

and if you have tabs (as you will in emacs-lisp-mode):

```
There are text properties here:
  fontified            t
  indent-bars-display  [Show]
```

and clicking on `[Show]`:

```
#("        " 2 3
  (face indent-bars-1)
  4 5
  (face indent-bars-2)
  6 7
  (face indent-bars-3))
```

(i.e. "display this tab as the equivalent spaces, with 3 bars on there").  Then maybe take a look at the value of `face-remapping-alist`. Should look something like:

```
((indent-bars-3
  (nil indent-bars-current-face)
  indent-bars-3)
 (indent-bars-ts-3
  (nil indent-bars-ts-current-face)
  indent-bars-ts-3)
 (indent-bars-current-face
  (:filtered #1=(:window indent-bars-whr 462337)
	     (:stipple
	      (7 1 "")))
  indent-bars-current-face)
 (indent-bars-face
  (:filtered #1#
	     (:stipple
	      (7 15 "")))
  indent-bars-face)
 (indent-bars-ts-current-face
  (:filtered #1#
	     (:stipple
	      (7 1 "")))
  indent-bars-ts-current-face)
 (indent-bars-ts-face
  (:filtered #1#
	     (:stipple
	      (7 15 "")))
  indent-bars-ts-face))
Local in buffer indent-bars.el; global value is nil
```

**Comment by jdtsmith** [comment]
> other people will have similar issues,

Highly unlikely that I wouldn't have heard about this kind of performance degradation by now.  Why don't you set `font-lock-maximum-decoration=nil`, restart `emacs-lisp-mode`, and see if that improves things?

**Comment by shipmints** [comment]
Thanks for your patience. indent-bars seems to behave as intended, is what I meant. My experience with its results is what's abnormal. Assigned text properties are correct. font-lock-mac-deco settings have no performance effect. I'll continue to be perplexed. Perhaps I should try another Emacs build. The one I use is https://emacsformacosx.com/ and I've been using those builds for a long time.

**Comment by jdtsmith** [comment]
I still am unable to reconcile the 5ms per line-move benchmarking your report with "it's unusable".  The former should be very "usable".  

Perhaps you have lots of other stuff on your post-command-hook.  You could starting removing things one at a time from that and see when performance thaws.

**Comment by shipmints** [comment]
I've looked. Ain't nothing out of the ordinary and if there were, it would show up on the profiler. It's just a slow ```line-move``` that results from the extra text properties that's visible. I'll continue plugging away, I like your software and the other indent highlighters I tried were not for me, when they worked at all.

**Comment by jdtsmith** [comment]
Slow and variable line-move simply must come from pre-command or post-command hook.  So worth investigating.

**Comment by alphapapa** [comment]
FWIW, @shipmints, I'd recommend that you try to reproduce the problem using the same Emacs init dir (i.e. `init.el` and `elpa/`) on a different platform, like Linux (even if in a VM on your Mac).  It's not impossible that the third-party build you're using is involved, even though it has had a generally good reputation.

**Comment by shipmints** [comment]
post-command-hook is minimal

Its value is
(corfu--auto-post-command indent-bars--highlight-current-depth eldoc-schedule-timer jit-lock--antiblink-post-command t)
Local in buffer bufferlo.el; global value is 
(global-font-lock-mode-check-buffers global-corfu-mode-check-buffers)

Next up, yep, another Emacs build.

**Comment by jdtsmith** [comment]
Nothing unusual, but easy to remove things (including `indent-bars--highlight-current-depth`, which I thought you had disabled for testing?). `M-x corfu-mode` and `M-x eldoc-mode`, for example.

**Comment by shipmints** [comment]
Just downloaded this to try https://github.com/jimeh/emacs-builds/releases/tag/Emacs-29.4 and holy shite its much better. Not sure the provenance but it was easy. I ran off the mount, didn't even install it. If the provenance proves out, I'm switching immediately. I still wonder, though, what other https://emacsformacosx.com/ users will experience. If I find any issues using this build, I'll let you know.

**Comment by jdtsmith** [comment]
Weird, but good to hear.  I've heard `--with-mac-metal` sometimes causes painful graphical slowdowns, so have abandoned it in my builds.  `native-comp` also might contributing, if you didn't have that before.

**Comment by jdtsmith** [comment]
I download Emacs for MacOSX, which I had never used.  It indeed has no native comp.

By benchmark, `(line-move 1)` in prism.el takes:

- no indent-bars: 4.3ms
- indent-bars without current depth highlight: 5.6ms
- indent-bars with current depth highlight: 5.6ms
- indent-bars with current depth highlight with 0 delay: 5.4ms

Interactively though, I can confirm your slowdown.  When you move down to areas with lots of bars, it definitely bogs down. I was able to move 471 lines "by hand" in 30s, corresponding to 64ms per move on average.  But without indent-bars I could only get 616 lines in 30s (49ms per).  So better, but still dog slow.  These are both "noticeable".  Nowhere near 1s as you report (which I suspect was a gross exaggeration).  But noticeable.  Something must be wrong with redisplay in that build.

You could give brew emacs-mac a try.  It's fast, and has stipple support.

**Comment by shipmints** [comment]
Thanks for taking a look. I'm working through things with https://github.com/jimeh/emacs-builds/releases/tag/Emacs-29.4 and so far, so good. This build even fixed that the NS build I was using didn't support setting the frame internal-border color which I use to indicate a test environment; i.e., $ emacs --test and I also change the active mode-line background. It's too easy to get confused between multiple running sessions without a visual indicator. I do have a local emacs git repo clone for reference and I tried to build it on Mac but it's a pain in the neck vs. a more conventional unix environment.
