### ISSUE TITLE
Blank without indicator in C++

### ISSUE THREAD

**Issue by aburlot** [jdtsmith/indent-bars#65]
Hi! Really nice package. 
I have a small issue with blanks between instruction as you can see on the following picture
![indent-bars-2](https://github.com/user-attachments/assets/88ab2c90-147c-4a6f-8945-e7e9bdda86de)
There are no indicators in from of the `if` or the `{`. I have set `indent-bars-display-on-blank-lines` to `t`.  Is it normal? I do not use tree-sitter C++ mode. I did not find any relevant options in the documentation you provide. Am i missing something?

**Comment by aburlot** [comment]
Two updates. If I put the brace just after the `if` instruction, the blank diseappears and the indent bars is there.  For the `for` loops, the cause seems to be that they are not followed by `{}`. If I add one _on the same line_ (`for (int i = 0; i < n; i++) {`, it works fine. If the brace is on the next line, we are back on the first update.

**Comment by jdtsmith** [comment]
Did you try turning off `indent-bars-no-descend-lists`?  It's likely that the syntax is such that `{`/`}` are considered a list.  If you'd like to post the code and mode used I can take a look.

**Comment by jdtsmith** [comment]
Indeed c-mode-derived modes seem to recognize as `{`/`}` as list syntax.  I have pushed an addition in dab1862 which allows you to configure `no-descend-lists` to be a list of open-paren chars to recognize.  E.g. `'(?\( ?\[)` to allow only round and square open parens to establish a list context.  

Give a try and see how that works for you.  You probably want to set this locally in c-derived modes.

**Comment by aburlot** [comment]
Thanks for the quick fix! Yes it was C/C++. I'll have to wait for the update in emacs packages. Any idea when it will be available there?

**Comment by jdtsmith** [comment]
The hope was you could clone the repo and test this with master, before a release is made.  You can easily just `M-x emacs-lisp-byte-compile-and-load` and give a try.

**Comment by aburlot** [comment]
Ok, just tried it. Looks like it works. I used this:
```cpp
// Example program
#include <iostream>
#include <string>

int main()
{
  const int aa = 0;
  if (aa == 0)
    {
      const bb = 10;
      for (int i = 0; i < bb; i++)
        {
          std::cout << i << "\n";
        }
    }
}

// Local Variables:
// indent-bars-no-descend-lists: '(40 91)
// End:
```
which gives this result:
![indent-bars](https://github.com/user-attachments/assets/e1e9aa88-844b-42b3-a501-2655909a9772)

**Comment by jdtsmith** [comment]
Great, thanks.  Can you also try a long function call that spans multiple lines to see if that works as you'd expect?

**Comment by aburlot** [comment]
Works like a charm.
```cpp
// Example program
#include <iostream>
#include <string>

int main()
{
  const int aa = 0;
  if (aa == 0)
    {
      const int bb = 10;
      for (int i = 0; i < bb; i++)
        {
          std::cout << i << "\n"
                    << i << "\n"
                    << i << "\n"
                    << i << "\n";
        }
    }
}

// Local Variables:
// indent-bars-no-descend-lists: '(40 91)
// End:
```
gives me
![indent-2](https://github.com/user-attachments/assets/a9061fa0-1bd7-4b3d-b7fe-dbfe5bf45a77)
