### ISSUE TITLE
indent bars not drawn for indented elisp properties

### ISSUE THREAD

**Issue by shipmints** [jdtsmith/indent-bars#69]
Obviously minor. Not sure if this is something I can configure.

<img width="1714" alt="image" src="https://github.com/user-attachments/assets/64460c14-c285-4dde-b425-519fc38789d4">

**Comment by shipmints** [comment]
Nice to finally be able to use this properly!

**Comment by jdtsmith** [comment]
This results from `indent-bars-no-descend-lists` being on; you can disable it for this mode (and probably should).  At the location of the properties here, the controlling list is the `frameset-restore` one, so no additional bars (other than the first) are added on lines at that level.   Deeper nested levels (like the `(when...`) have the same behavior (just ...deeper, see e.g. the `(mapc...`).

`indent-bars` is really designed for languages for which one indent-spacing = one level deeper in the hierarchy.  Lisp obviously breaks that assumption quite frequently.

**Comment by shipmints** [comment]
Works perfectly. So great. Can't tell you how happy I am to have wasted days on something I couldn't have controlled to begin with, OMG.

**Comment by shipmints** [comment]
Not sure what I'm supposed to be seeing but setting `indent-bars-no-descend-lists` to nil or t produces the same look.  I'm currently hacking `progress-reporter-do-update` and I've attached screenshots for t and nil.  User error or user expectations mismatch, likely.

<img width="1230" height="947" alt="Image" src="https://github.com/user-attachments/assets/0793279d-6463-4f62-b62f-2accce962ac1" />

<img width="1230" height="947" alt="Image" src="https://github.com/user-attachments/assets/405f9c5c-7e02-4c9f-b0b0-b4f90e398649" />

**Comment by jdtsmith** [comment]
Here's a particularly deep nesting that looks "ok" with the new setup:

<img width="580" height="300" alt="Image" src="https://github.com/user-attachments/assets/fd9515d2-1f5e-4977-80e5-6b1c45be1b92" />

I don't think elisp will ever look _that_ great since it respects `lisp-data-indent` only very little.

**Comment by jdtsmith** [comment]
So does `define-error` look like this for you with the latest?  If not can you send a short reproducer from `emacs -Q`?

**Comment by shipmints** [comment]
I get the same look, yep.
