### ISSUE TITLE
Please add the package to melpa

### ISSUE THREAD

**Issue by justinjk007** [jdtsmith/indent-bars#7]
Please add the package to [melpa](https://melpa.org/#/)

Straight package manager seems like a lot of work to integrate into after all these years of package.el

**Comment by justinjk007** [comment]
More details on how to add to melpa here : https://github.com/melpa/melpa/blob/master/README.md#contributing

**Comment by justinjk007** [comment]
For now I have cloned the repo and set the location to load like the first example on how to use the package

**Comment by jdtsmith** [comment]
I'll consider nongnu-elpa once all the kinks are sorted out.  Note that emacs-29 can load packages direct from GitHub.

**Comment by justinjk007** [comment]
Oh I didn't know I can load packages from github on emacs 29, just reading it here now : https://blog.phundrak.com/emacs-29-what-can-we-expect/#install-packages-from-source-with-package-dot-el
