### ISSUE TITLE
scrolling upwards broken on macOS with non-stipple indent bars

### ISSUE THREAD

**Issue by dcolascione** [jdtsmith/indent-bars#70]
When indent-bars is enabled and stipple is disabled (preferring characters instead), scrolling upwards with the mouse wheel does not make progress.

I am trying this configuration with latest Emacs master

```
(setopt
 indent-bars-color '(highlight :face-bg t :blend nil)
 indent-bars-prefer-character t
 indent-bars-color-by-depth nil
 indent-bars-highlight-current-depth nil
 indent-bars-display-on-blank-lines t)
```

Scrolling seems to work fine with stipple enabled, but the NS build's support for stipple backgrounds appears broken somehow, so I'd prefer to use the character mode.

**Comment by jdtsmith** [comment]
I don't see this behavior on NS.  Can you enable debug-on-error and/or report anything from the `*Messages*` buffer, especially pertaining to font-lock?

**Comment by dcolascione** [comment]
Weird. I can't repro anymore either. I'll close this until I see it again. Sorry for the noise!

**Comment by bravosierrasierra** [comment]
d12frosted/emacs-plus/emacs-plus@30 have this bug :(
