### ISSUE TITLE
Don't show indentation bars inside multi-line ePython strings

### ISSUE THREAD

**Issue by paaguti** [jdtsmith/indent-bars#71]
I'm using the 'old-style' example, just added not to show stipples on empty lines.
Indent bars shouldn't appear on multi-line Python strings:

<img width="724" alt="Captura de Pantalla 2024-09-29 a las 8 24 47" src="https://github.com/user-attachments/assets/040807ae-0c5a-4f83-8934-830129cad76e">

**Comment by jdtsmith** [comment]
I presume you have `indent-bars-no-descend-string=t`.  The rule employed here is that indentation will be added only _one level deeper_ than the bar indent of the starting line of the string, which is what's shown here.  I find it useful to have one bar inside multi-line docstrings, ala:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/36848bd4-c771-4ec0-8795-c5c38e14d30e">

The same algorithm is used for lists, and there it's quite essential.  I suppose I could allow `indent-bars-no-descend-string` to equal a number of additional bars relative to the string starting indent, where `0` would indicate none.   I suspect you might miss those bars elsewhere though.

**Comment by jdtsmith** [comment]
In d60a632 I've added the possibility to set `indent-bars-no-descend-string=all` to inhibit all bars within multiline strings.  Give it a test and see how that works for you.
