### ISSUE TITLE
Nested indent lines should terminate on blank lines

### ISSUE THREAD

**Issue by printfdebugging** [jdtsmith/indent-bars#76]
Hi, thanks for the cool package! I have this minor issue (in the image) where ether the indent line doesn't show at all the levels for blank lines, or whenever they show up, they extend fully till the next line. Like in the shared example, I would expect the inner indentation line to stop at `|	|	user.Username)`, while the outer indentation line should continue till the end of the function., somewhat like the second image from neovim.
![image](https://github.com/user-attachments/assets/d076f8f2-9203-4c65-8b94-4564c94fc45f)
neovim's indent guides
![image](https://github.com/user-attachments/assets/cd6ed96c-3f89-4a9d-b4c2-1e2934d5a26a)
Here's my configuration, if I am missing something which already does that
```
(use-package indent-bars
  :config
  (require 'indent-bars-ts) 		; not needed with straight
  :custom
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
   (setq
    indent-bars-color '(highlight :face-bg t :blend 0.1)
    indent-bars-pattern "."
    indent-bars-width-frac 0.2
    indent-bars-pad-frac 0.4
    indent-bars-zigzag nil
    indent-bars-starting-column 0
    indent-bars-color-by-depth nil
    indent-bars-highlight-current-depth nil
    indent-bars-display-on-blank-lines t)
  :hook ((python-base-mode yaml-mode go-mode text-mode prog-mode) . indent-bars-mode))
```

**Comment by printfdebugging** [comment]
Also for some reason, this is not activating indent-bars in any of the prog modes. Please suggest something for that as well :)

**Comment by jdtsmith** [comment]
I don't agree with "should". The rule for blank line bars is mentioned in `display-blank-lines`:

> It is ambigious how many bars to draw on each line in a stretch
of blank lines, so this uses the maximum depth of the surrounding
line indentation, above and below. 

The reasoning here is "what would the depth of these bars be, if code were continued at this level from above or below".  Which to my eye is the better of two ambiguous choices.  

If you can make the case that many users would expect the _least_ of the surrounding non-blank bar depth and can work up a few more examples with different plausible adjacent depths, I would consider adding a config option for that.

**Comment by jdtsmith** [comment]
`indent-bars-mode` toggles the mode in a buffer.   By including both generic modes like `prog-mode` and more specific modes, you are repeating yourself, which toggles it on and then off.  So either remove prog-mode if you only want those specific modes, or remove the specific modes from the hook list.

**Comment by printfdebugging** [comment]
Let's start with the example that you talked of. It's a python conditional, where the scope is decided by the indentation. Things on the same indentation level fall under the same scope. The Indentation line are more-or-less one tab behind the next scope, or putting it otherwise, the next scope is one tab ahead of the indentation lines. It would look very awkward if the the scope spreads unneccessarily, as depicted in line 2, or let's put it otherwise "it looks very elegant when the indent lines are in sync with the scope of the code written. (image 2 showing the  awkward example)
![image](https://github.com/user-attachments/assets/6dce35a5-cf38-463c-8456-5ccdc91dbd60)
![image](https://github.com/user-attachments/assets/56cd7bfd-5cf6-4809-868f-0a8777b0fd3a)

Now talking of languages which depend on curly braces for scope, like C and C++. Correct me if I am wrong, but aren't indentation lines just visual indications of scope? 
![image](https://github.com/user-attachments/assets/e6992416-ad56-4e78-955c-ed6153aeb1b2)
This one is using our plugin. I am a novice programmer so might not even know what scope actually is, but just felt a little odd looking at these things pointed out. The plugin is already a huge improvement over what we had, and I am very happy with it. What do you say on these scope issues? Are these valid?
![image](https://github.com/user-attachments/assets/0186cfbc-254c-4d12-8161-e689ee44f031)

**Comment by printfdebugging** [comment]
![image](https://github.com/user-attachments/assets/9a0432aa-ffe2-4864-98ff-1a893f595bec)
Also here you can see how it compares in bash mode

**Comment by printfdebugging** [comment]
```
(use-package indent-bars
  :config
  (require 'indent-bars-ts)
  :custom
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  :hook ((python-base-mode c-mode c++-mode sh-mode yaml-mode) . indent-bars-reset))
(setq
 indent-bars-color '(highlight :face-bg t :blend 0.2)
 indent-bars-pattern "."
 indent-bars-width-frac 0.2
 indent-bars-pad-frac 0.4
 indent-bars-starting-column 0
 indent-bars-zigzag nil
 indent-bars-color-by-depth nil
 indent-bars-highlight-current-depth nil
 indent-bars-display-on-blank-lines t)
```
with this configuration, I am still not getting these indent guides even though the mode is enabled and they only show up when I disable and enable it again from the minibuffer in those buffers. Here are my emacs config files (https://gitlab.com/printfdebugging/dotfiles/-/tree/main/roles/emacs/files), you can test them without much issue (it might search for an org roam directory in ~/repos/notes)

**Comment by printfdebugging** [comment]
I tried both `indent-bars-mode` and `indent-bars-reset` there in the hook, and both didn't work

**Comment by jdtsmith** [comment]
Not able to follow all your arguments, but your confusion may stem from the mistaken idea that indent-bars is adding bars to indicate something deep about the structure of the code.  It is not.  It is simply adding (or inventing) bars at a given indentation depth based on the configured indent spacing in your buffer.  Now some modes or languages allow weird continuations, like your bash example.  That's poor language design IMO, and indent-bars knows nothing about the notion that `||` at the end of a line can continue to the next line.  Indenting that next line is arbitrary.  You can wrap all those if args in parens, and that will avoid deeper bars.  But all that said, I look at that example, and the left looks _way_ better to my eye than the right.  Here is the `function`, here is the `if..elif..fi` block. 

I don't see what's wrong with line 2 in your first example above.  In that case, because of the comment, it is now _clear_ that you have out-dented, so no bar.  If you removed the comment, it would indeed have two bars, and if you hit two returns below the last statement in the if block, your cursor would be in the right place.  

> aren't indentation lines just visual indications of scope?

**No**, they indicate _indentation_.  See above.  

Like this example:

```c
// this indentation line is clearly wrong when thinking...
```

But that comment is nested deeper?  Why?   At a deeper indent, it will get another bar.

If you want "real scope" highlighting look into `indent-bars` tree-sitter integration, but it will not change which bars appear (just how they are styled).

**Comment by jdtsmith** [comment]
If you turn off `indent-bars-no-descend-lists` in bash mode, that will fix your function example.   Alternatively, you can omit `{`/`}` from consideration as "lists" (despite the syntax indicating they are).  See the docs for `indent-bars-no-descend-lists`.

**Comment by jdtsmith** [comment]
I can't test your full emacs config and I don't understand why you're unable to load it in the hook, which works elsewhere.  Likely some misconfiguration.

Can you please try this again starting from `emacs -q` loading _only_ `indent-bars` and one of your modes, and provide a reproducer if it shows the same issue?

**Comment by jdtsmith** [comment]
RE:

```c
\\ this part is not in the above function declaration's scope, and hence the
\\ indentation line shouldn't be extended beyond the Arg4 declaration.
```

Assuming you are using treesitter, one other thing to try, which actually _does_ change which bars are drawn and could "fix" this, is `indent-bars-treesit-ignore-blank-lines-types`.  E.g., I set that to `'("module")` which means no blank lines are filled at the top-level module.  You could add class or whatever you wanted to that.  

The only other algorithmic tweak I could offer an option for is "on a blank line, look to the nearest non-blank adjacent lines above/below, and add the _least_ number of bars you see".  Right now I add the "most" bars.  See if that "least" would satisfy you in all the cases.  If so I'll consider adding it as an option.

**Comment by printfdebugging** [comment]
yes, I think having a "least" bars option would make sense. It would then eliminate most of the indent bars going beyond "scope" issues.

**Comment by jdtsmith** [comment]
See 4b8114e for the ability to set `display-on-blank-lines=least`.  Please give this a test!

**Comment by printfdebugging** [comment]
![image](https://github.com/user-attachments/assets/f4385da3-3319-488e-9d9e-75f1c5e80c3f)
:) works like a charm! It's not in elpa though, I had to clone the repo and load the file. How long does it take for it to refresh in there?

**Comment by jdtsmith** [comment]
I'll make a release shortly.
