### ISSUE TITLE
Bars are broken up on core .el files

### ISSUE THREAD

**Issue by jreicher** [jdtsmith/indent-bars#77]
I think the cause is that these files have the emacs-ish mix of tabs and spaces, and I am not using stipples, so while the indentation appears as spaces the bars are present, but when the spaces stack up enough to convert to a tab, indent-bars doesn't convert the tab back to individual chars and so the bars disappear. But that's a guess; please let me know what I can do to test further.

**Comment by jdtsmith** [comment]
Not likely, indent-bars works fine with tabs.  More likely is you have `indent-bars-no-descend-lists=t` on in Elisp, which does not allow bar depth to increase inside lists.  Since Elisp is pretty much entirely continued lists, the will lead to the appearance of "broken" bars.  Try setting that to nil and restarting.

**Comment by jreicher** [comment]
Restart? Reverting the buffer is not enough?

**Comment by jdtsmith** [comment]
Or `M-x indent-bars-reset`

**Comment by jreicher** [comment]
It didn't fix the issue. It occurs on all and only the lines that have tabs resulting from space indentation from previous lines "adding up"

**Comment by jdtsmith** [comment]
What mode is this?  Is `indent-tabs-mode` set?

**Comment by jreicher** [comment]
All the lines with bars have spaces, and all the ones without have tabs. Otherwise it's a random example. It happens in almost all core .el files.

![image](https://github.com/user-attachments/assets/d6fdaca0-8de7-4df7-87c9-3b1578b1b022)

**Comment by jdtsmith** [comment]
> What mode is this? Is indent-tabs-mode set?  

Seems from the screenshot like regular `emacs-lisp-mode`.  I had asked about `indent-tabs-mode`, but you didn't respond.  As an aside, please read and respond to all questions when seeking help --- it really speeds up the diagnosis process.

I suspect you have configured `indent-tabs-mode=nil`, even though you are visiting a file which is indented with tabs.  That is an mis-configuration on your part.

Here's how it should look with the default `indent-tabs-mode=t`:

<img width="596" alt="image" src="https://github.com/user-attachments/assets/9b516ba1-c285-42dd-83ac-f5180abe2d67">

**Comment by jreicher** [comment]
Sorry I missed your question about `indent-tabs-mode`. You are right that setting this to `t` fixes, but I think it's a valid config to have it as `false` for my own editing; it's not my choice that other people's files I'd like to view were edited with it active, and I'm not sure the best way to accommodate this of my own editing and reading other people's files.

For the moment I've put

```
((lambda nil
   (setq indent-tabs-mode t))
 indent-bars-reset)
```

in `emacs-lisp-mode-hook` to make elisp an exception to my preferred editing style.

**Comment by jdtsmith** [comment]
This is an age-old problem.  You can take it as a sign of mismatch between your tabs mode and the file.  Note that many modes explicitly override your setting of `indent-tabs-mode`, so it's best to pick an indentation style per mode and stick to it.   Do you want to edit elisp/view files using spaces, or are you OK using tabs as the default, as emacs itself does?  If so,  something like should work:

```elisp
(add-hook 'emacs-lisp-mode-hook
	  (lambda ()
	    (setq-local indent-tabs-mode t
			indent-bars-no-descend-lists nil)
	    (indent-bars-mode 1)))
```

If you want to mix and match different styles and files within one mode, you should look into [dtrt-indent](https://github.com/jscheid/dtrt-indent).

**Comment by jdtsmith** [comment]
I've added an FAQ for this.
