### ISSUE TITLE
Interaction with whitespace-mode

### ISSUE THREAD

**Issue by brownts** [jdtsmith/indent-bars#79]
I'm seeing an issue when I try to use `global-whitespace-mode` with `indent-bars-mode` when the tree-sitter support in `indent-bars-mode` is enabled.  It seems that whatever the fontification that existed with respect to `whitespace-mode` cannot be changed while `indent-bars-mode` is enabled.  This seems to only occur when the tree-sitter support is enabled.  What seems to happen is that anything that would cause new fontification for whitespace mode (i.e., insertion of tab or trailing whitespace) is not highlighted as expected.  Additionally, when I toggle `global-whitespace-mode` off, the fontification is not removed from the buffer.

I've attached a minimal `init.el` which will set things up to demonstrate this issue.  Additionally, I've attached a `hello_world.c` with included trailing whitespace and tabs to use with this configuration.

In this particular example, I have a couple lines with trailing whitespace and a couple lines with an initial tab (i.e., the "printf" and "return" lines).  These are initially highlighted since the whitespace global mode is enabled.  However, I've also bound "C-&lt;tab&gt;" to be able to toggle the whitespace mode on and off at will.  When I attempt to toggle whitespace while `indent-bars-mode` with tree-sitter support enabled, nothing happens.  By this, I mean the fontification in the buffer doesn't change.  You'll notice the "ws" minor mode toggle on the mode line, and the message in the echo area, when I press C-&lt;tab&gt; to toggle whitespace mode on/off, but the fontification doesn't change.

I have to disable the tree-sitter support in `indent-bars-mode` in order to be able to successfully use whitespace mode.  However, it appears it's not sufficient to just disable `indent-bars-treesit-support` and then run `indent-bars-reset`.  After setting `indent-bars-treesit-support` to nil, I have to reload the file (e.g., `revert-buffer`) before it seems to work properly.  I would have expected that `indent-bars-reset` would have been sufficient.

On a side note, I don't think this is related, but I noticed the following discrepancy:
- `indent-bars-ts--disable` is always added to `indent-bars--teardown-functions`, but never removed.
- `indent-bars-ts--teardown` is always removed from `indent-bars--teardown-functions`, but never added.

The following screenshot shows just after disabling whitespace mode.  Notice the "Global Whitespace mode disabled" message in the echo area and notice the fontification still active in the buffer.

[init.el.zip](https://github.com/user-attachments/files/17356040/init.el.zip)
[hello_world.c.zip](https://github.com/user-attachments/files/17356048/hello_world.c.zip)

![Screenshot_2024-10-13_10-41-06](https://github.com/user-attachments/assets/f8abc7c4-e5ae-4042-9db5-f9dbf880ae78)

**Comment by jdtsmith** [comment]
> On a side note, I don't think this is related, but I noticed the following discrepancy: indent-bars-ts--disable is always added to indent-bars--teardown-functions, but never removed. indent-bars-ts--teardown is always removed from indent-bars--teardown-functions, but never added.

Fixed in 388daf2.  

> I would have expected that indent-bars-reset would have been sufficient.

Aha, I didn't correctly anticipate users turning off treesit support after enabling `indent-bars` with it in a buffer.  This should be fixed in 7011038.

> I have to disable the tree-sitter support in indent-bars-mode in order to be able to successfully use whitespace mode. 

I looked into this.  `whitespace-mode` is very aggressive in its fontification, installing a post-command hook that does lots of unprotected `font-lock-flush`ing.  In this case it interferes with the fontification that `indent-bars-ts` does.  I'm not sure what the point of a `post-command-hook` is when simply highlighting whitespace; do you know?  It's especially egregious in that it isn't protected by a timer.  Honestly I'd personally  recommend `(remove-hook 'post-command-hook 'whitespace-post-command-hook t)` after it's initialized.  With that, it seems to work quite well (and faster).

In any case, I've pushed a fix in bed3d48 to wrap `font-lock-flush-function` to set the `pending` property (which `indent-bars-ts` uses to avoid refontifying everything when moving point).  Works with `whitespace-mode` (including its PCH) in my limited testing.

Please give all this a test on `main`.

**Comment by brownts** [comment]
> I'm not sure what the point of a `post-command-hook` is when simply highlighting whitespace; do you know? It's especially egregious in that it isn't protected by a timer. Honestly I'd personally recommend `(remove-hook 'post-command-hook 'whitespace-post-command-hook t)` after it's initialized. With that, it seems to work quite well (and faster).
> 

It looks like this is to handle face changes when nothing is actually modified in the buffer.  For example, when point is at the end of a line which contains trailing spaces, those trailing spaces aren't actually fontified (with the `whitespace-trailing` face) until point is moved away from the end of the line.  If you remove `whitespace-post-command-hook` from `post-command-hook`, you'll see that the face isn't updated when point is moved to or from the EOL which contains trailing spaces.  I don't know all of the capabilities of `whitespace-mode`, but I'm familiar with that specific behavior which appears to require the functionality in the `whitespace-post-command-hook`.

> In any case, I've pushed a fix in [bed3d48](https://github.com/jdtsmith/indent-bars/commit/bed3d48e2639bff07dee9a4190e8b2a405cf1a71) to wrap `font-lock-flush-function` to set the `pending` property (which `indent-bars-ts` uses to avoid refontifying everything when moving point). Works with `whitespace-mode` (including its PCH) in my limited testing.
> 
> Please give all this a test on `main`.

Using the previous example file, it kind of works.  If I do nothing different, attempting to toggle `global-whitespace-mode` off/on behaves the way it was before, where it appears the font locking is frozen.  However, if I toggle `indent-bars-mode` off and then back on, then I can successfully toggle `global-whitespace-mode` after that point.

**Comment by jdtsmith** [comment]
> those trailing spaces aren't actually fontified (with the whitespace-trailing face) until point is moved away from the end of the line.

Actually they are fontified and then unfortified in a post-command-hook!  So the idea is that the current line has its whitespace highlighting removed?  

> Using the previous example file, it kind of works. If I do nothing different, attempting to toggle global-whitespace-mode off/on behaves the way it was before, where it appears the font locking is frozen. However, if I toggle indent-bars-mode off and then back on, then I can successfully toggle global-whitespace-mode after that point.

Probably this was a one time thing to get indent-bars to actually wrap the flush function.  Try again in a clean session (which is a good thing to try anyway if encountering issues).

**Comment by brownts** [comment]
> > those trailing spaces aren't actually fontified (with the whitespace-trailing face) until point is moved away from the end of the line.
> 
> Actually they are fontified and then unfortified in a post-command-hook! So the idea is that the current line has its whitespace highlighting removed?
> 

Removed or added.  If point was at the EOL, and then moved, the "trailing whitespace" highlighting needs to be added.  If it was not at the EOL and then moved there (e.g., "C-e"), "trailing whitespace" highlighting needs to be removed.

> > Using the previous example file, it kind of works. If I do nothing different, attempting to toggle global-whitespace-mode off/on behaves the way it was before, where it appears the font locking is frozen. However, if I toggle indent-bars-mode off and then back on, then I can successfully toggle global-whitespace-mode after that point.
> 
> Probably this was a one time thing to get indent-bars to actually wrap the flush function. Try again in a clean session (which is a good thing to try anyway if encountering issues).

I tried this multiple times, restarting Emacs each time.  The behavior was repeatable.  You should be able to observe this behavior with the configuration I had originally provided.  I also traced this and its likely due to the fact that the global mode gets activated after `indent-bars-mode`.

```text
======================================================================
1 -> (indent-bars-mode)
1 <- indent-bars-mode: t
======================================================================
1 -> (whitespace-mode)
1 <- whitespace-mode: t
```

**Comment by jdtsmith** [comment]
This is complicated; `font-lock` is overwriting variables based on load order.  I have deferred finalization of `indent-bars-ts` in the `font-lock-mode-hook` on initial start (but not on reset/toggle).  This _should_ allow you to start these modes in either order.  

But generally this advice still holds:

> the strong recommendation is to enable `indent-bars` last, after any other package which overrides `font-lock` in this way have been loaded.

**Comment by jdtsmith** [comment]
For posterity, here's what the call sequence now looks like (in a python TS buffer) with the deferred finalization:

```
======================================================================
1 -> (python-ts-mode)
| 2 -> (python-base-mode)
| | 3 -> (prog-mode)
| | 3 <- prog-mode: nil
| 2 <- python-base-mode: nil
| 2 -> (outli-mode)
| 2 <- outli-mode: t
| 2 -> (indent-bars-mode)
| | 3 -> (indent-bars--ts-mode 1)
| | | 4 -> (indent-bars-ts--setup python)
| | | 4 <- indent-bars-ts--setup: (indent-bars-ts--finalize-jit-lock t)
| | 3 <- indent-bars--ts-mode: t
| 2 <- indent-bars-mode: t
| 2 -> (jit-lock-mode nil)
| 2 <- jit-lock-mode: nil
| 2 -> (font-lock-turn-on-thing-lock)
| | 3 -> (jit-lock-mode t)
| | 3 <- jit-lock-mode: (jit-lock-function)
| 2 <- font-lock-turn-on-thing-lock: (font-lock-extend-jit-lock-region-after-change t)
| 2 -> (indent-bars-ts--finalize-jit-lock)
| 2 <- indent-bars-ts--finalize-jit-lock: nil
1 <- python-ts-mode: nil
```

**Comment by jdtsmith** [comment]
Let me know if this fixes the issue you were seeing.

**Comment by brownts** [comment]
I apologize for the delayed response.  I've tested this more with your latest changes and it now appears to be working properly with `whitespace-mode`.  Thank you for all the work on this and your persistence in chasing these issues down, it's very much appreciated.
