### ISSUE TITLE
Background transparency of indent-bars

### ISSUE THREAD

**Issue by Dickby** [jdtsmith/indent-bars#8]
With alpha-background set to have a transparent background, the background of the indent-bars stays opaque.

**Comment by jdtsmith** [comment]
You mean via `:background`?  Can you share an image?

**Comment by StrictlyMonad** [comment]
I suspect that you are doing something wrong, because I am not experiencing the same issue at all.

**Comment by Dickby** [comment]
![20230801_21h33m23s_grim](https://github.com/jdtsmith/indent-bars/assets/10100765/3ae3bf92-566a-4760-9348-f502bdcfa4b0)

GNU Emacs 30.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-08-01

compiled with pgtk running under wayland.

I get this with emacs -Q and just loading `compat` and `indent-bars`

**Comment by jdtsmith** [comment]
I suspect this is a general feature of stipple drawing in your Emacs version.  Can you try the [test](https://github.com/jdtsmith/indent-bars#testing-stipples)?  If it shows the same thing, you may need to submit a bug report upstream.

**Comment by Dickby** [comment]
How should the result of the text look like with alpha-background used for transparency?
The tests result looks like your example picture, should it be transparent? And if so, should the transparency be affecting the red bars, or the black gaps in between?

**Comment by jdtsmith** [comment]
Sorry can you remove the `:background "red"` and retest?  May guess I you'll blue bars, but their background will be an opaque version of your normal BG color.

**Comment by Dickby** [comment]
![20230803_13h54m59s_grim](https://github.com/jdtsmith/indent-bars/assets/10100765/78076114-27a3-4f18-85c0-312c218cd0e9)

**Comment by jdtsmith** [comment]
OK, this appears to be a display bug for stipple in whatever version you are using (let me know `M-x emacs-version`); i.e. stipple drawing does not respect `alpha-background`.  Can you report this upstream, and link the bug report here?  In the meantime, you can use `indent-bars-prefer-character` if you'd like a simple character-based bar, which should (I think) no exhibit this bug.

**Comment by Dickby** [comment]
I reported the bug:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=65042

**Comment by jdtsmith** [comment]
It would be good if you followup with a simple reproducer that does not include `indent-bars`.

**Comment by Dickby** [comment]
I added a link to this issue in the bug report.
This diskussion mentions your test without the `:background red`.
Don't you think this is enough?

**Comment by Dickby** [comment]
Done.

**Comment by Dickby** [comment]
The latest patch provided by Po Lu in the bug report conversation fixes this problem.
You can close this issue if you want, or i will close it as soon as the fix is merged.

**Comment by Dickby** [comment]
I'm trying, but github doesn't let me updload another image for some reason it keeps telling me 'Something went relly wrong, and we can't process that file'. What a wonderful well designed platform this is!
I will try later today

**Comment by Dickby** [comment]
![picture](https://github.com/jdtsmith/indent-bars/assets/10100765/6f28875c-a2c7-4700-9538-854cf4adf486)
