### ISSUE TITLE
Support for mixed indent offset in python

### ISSUE THREAD

**Issue by gongzhitaao** [jdtsmith/indent-bars#80]
In my python setup, I have mixed indent offset.  The default is 2, but multi-line statements has 4.  See the following

![Screenshot from 2024-10-15 15-06-59](https://github.com/user-attachments/assets/a16da66e-4a25-4af5-9bb7-7a5cd86c7eee)

In this case, the last indent bar (where the block cursor is on) is not needed.

Question: Is there a way to make it disappear?

`highlight-indent-guides` does not have this problem but misses the blank lines.

**Comment by jdtsmith** [comment]
See `indent-bars-no-descend-list` which until recently was default.   This is documented.
