### ISSUE TITLE
Weird Indentation Bars in indent-bars Mode

### ISSUE THREAD

**Issue by mrprofessor** [jdtsmith/indent-bars#84]
While using indent-bars mode in Emacs, I’m encountering an issue where each indentation level in my code is appears to be flanked by two dashed lines, rather than a single line per indentation level. 

<img width="165" alt="image" src="https://github.com/user-attachments/assets/a5be0f4f-d74c-41e9-ac29-e7d578f20ba9">

my config:

```emacs-lisp
(use-package indent-bars
  :hook ((prog-mode) . indent-bars-mode))
```

**Environment**
**Emacs Version**: `"GNU Emacs 30.0.91 (build 1, aarch64-apple-darwin24.0.0, NS appkit-2566.00 Version 15.0 (Build 24A335))
 of 2024-09-26"`
**Indent Bars Version**: `v0.8.1`
**Theme**: `leuven/leuven-dark` (doesn't work with other themes either)

**Comment by jdtsmith** [comment]
This is a limitation of stipple display.  Is this in a non-left-hand window?  Does it persist with `M-x indent-bars-reset`?

**Comment by mrprofessor** [comment]
> This is a limitation of stipple display (which you should never see). Is this in a non-left-hand window? Does it persist with `M-x indent-bars-reset`? Is your code offset from the window edge by any other package?

Hello!
Is this in a non-left-hand window? No
Does it persist with `M-x indent-bars-reset`? Unfortunately yes
Is your code offset from the window edge by any other package? Yes, I use diff-hl, but I have disabled everything and it didn't help.

I have checked with a minimal config and I still see this

<img width="459" alt="image" src="https://github.com/user-attachments/assets/c2bafb8d-5435-4d45-824a-34b6d03df1a5">



<img width="469" alt="image" src="https://github.com/user-attachments/assets/e3e1757e-2a12-4b8d-be60-bae72ee744d8">


My config
```elisp
(require 'package)
(setq package-archives '(("elpa"   . "https://elpa.gnu.org/packages/")
                         ("melpa"  . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

;; Initialize use-package on non-linux platforms
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(straight-use-package '(org :type built-in))

(use-package indent-bars
  :hook ((prog-mode) . indent-bars-mode))
  ```

**Comment by jdtsmith** [comment]
Is this with emacs -Q?  Do you see the same issue with Emacs 29 in your setup?

You hadn't mention org. Is this only in org mode src blocks?  It's challenging for indent-bars to work well there, since it needs to know the pixel offset of the window it is displayed in, and org creates a hidden buffer for code, fontifies it there, then copies the fontification back into the org buffer.

Check `(window-edges nil t nil t)` in the buffers you are experiencing this in.  This is what `indent-bars` uses to find out where the window starts (in pixel space).

**Comment by jdtsmith** [comment]
Added some [documentation](https://github.com/jdtsmith/indent-bars#org-mode-src-blocks) regarding org src blocks.
