### ISSUE TITLE
indent-bars-reset might need to be called after applying dir- or file-local variables

### ISSUE THREAD

**Issue by jreicher** [jdtsmith/indent-bars#88]
It's not uncommon for indentation-related settings to be in .dir-locals.el and the like, but these can be applied after the major mode hook that enables indent-bars-mode.

One tactic that appears to work is adding indent-bars-reset to hack-local-variables-hook. I'm not sure this is the best way, but if it is perhaps indent-bars should install that itself.

**Comment by jreicher** [comment]
This might have the added benefit of taking care of resets in other situations as it I think this hook is called regardless of whether such variables are present or not.

**Comment by jreicher** [comment]
Sorry it took a while to understand what you meant. I found this comment in `normal-mode` which I think is quite interesting, as it closely resembles what I've been asking about

```
  ;; Turn font lock off and on, to make sure it takes account of
  ;; whatever file local variables are relevant to it.
```

I've decided to use `find-file-hook` as it might be quite good for this purpose, calling `indent-bars-mode` on the condition `(derived-mode-p 'prog-mode)` (plus a few other things that are my preference)

**Comment by jdtsmith** [comment]
That could work, though sometimes you have a buffer without a file and want `indent-bars` on.  Emacs gives you tons of options, but it does introduce some complexity.  In the latest commit I have added a simple custom variable `indent-bars-defer-setup`.  Can you remove your `find-file-hook` etc. and try enabling this?  It only works if the only way you enable `indent-bars` is via a mode hook (which is typical).

**Comment by jreicher** [comment]
For the cases I've tested that works perfectly!
