### ISSUE TITLE
Hide repeated bars

### ISSUE THREAD

**Issue by walseb** [jdtsmith/indent-bars#9]
Hello!

Thank you so much for this package!

In order to wrap long blocks into multiple lines, I have massive indents in my code. This package creates a massive amount of indent bars in those spaces. Is there any way to hide the repeated indent bars? Here's an example:

![indent](https://github.com/jdtsmith/indent-bars/assets/2865774/c661ddfe-0a93-4d67-a6f3-1469d5505bac)

I would prefer if repeated bars could be hidden like so:
![indent-2](https://github.com/jdtsmith/indent-bars/assets/2865774/313329fc-2326-4c04-8f1e-af01eaf4b5bd)

Is there some way that this is possible to do? I didn't see any options for it.

Thank you!

**Comment by jdtsmith** [comment]
This would be a pretty significant change, since it requires understanding the structure of the code.  Not sure there is a robust method to do this generally.  I'm open to ideas; will leave this open.

**Comment by aciceri** [comment]
General and robust (and fast!) method for understanding the structure of code? It seems to be the perfect job for tree sitter!
Said this, I don't know the current tree sitter state for elisp, but there seems to be grammars available. For some reason if try to enable the tree sitter mode while in a elisp buffer my Emacs (29, native tree sitter) says `no language registered for major mode "emacs-lisp-mode"` but I never investigated this.

**Comment by jdtsmith** [comment]
Right. I've thought about using treesitter to avoid extra bars in function args, for example. Need config per language. Lisps are easy to parse and don't need treesitter for this, but you are basically always inside of an sexp, so it's hard to know how deep to go.  One bar deeper than the starting sexp column position perhaps?  They don't usually line up on indentation multiples.

**Comment by jdtsmith** [comment]
OK, I have included experimental `tree-sitter` support, along with another setting which prevents additional depth in strings and line-spanning comments.  Check the `treesit` branch and let me know how it goes.  

You have to configure the `tree-sitter` node types which are used to limit the indentation depth.  Example config for python:

```elisp
(use-package indent-bars
  :load-path "~/code/emacs/indent-bars"
  :custom
  (indent-bars-treesit-support '((python "argument_list" "parameters" "list" "dictionary"
					 "parenthesized_expression" "subscript")))
  :hook (python-mode . indent-bars-mode))
```

This basically stops descending past the opening line of function call argument lists and definition parameters, and lists/dicts/etc.  To try this with other languages which have `treesit` enabled, enable `treesit-explore-mode` and browse around for useful types.   FYI, `tree-sitter` is fast, but calculating indentation is about 5-10x slower with it enabled (but talking 5-10 µs or so, so pretty dang fast).   If it's working, it should look like:

<img width="515" alt="image" src="https://github.com/jdtsmith/indent-bars/assets/93749/b2057cb9-f551-44bd-a474-6fde0338c495">

**Comment by aciceri** [comment]
Brilliant! This package definitely is the best "indent bars package" on Emacs!
Still have to try this, but I'll let you know if I've problems when I finally try it.

At this point, since you already integrated tree-stiter, how difficult would be also highlight only the "vertical portion" of the current depth bar according to where the cursor is in the AST?
I don't know if I explained myself, I can open an issue with some examples if you prefer.

**Comment by jdtsmith** [comment]
> how difficult would be also highlight only the "vertical portion" of the current depth bar according to where the cursor is in the AST

You could pretty readily come up with some "containing node types" such that it traverses up to that level.  The problem then becomes the speed of highlighting as you move around.  It's so fast in indent-bars because it uses face-remapping, which obviously applies to all bars at that level.  I'd be loathe to give up this performance benefit, since that's one of the weakest areas of other packages I've used.

**Comment by jdtsmith** [comment]
I've made a change to how treesitter identifies wrapping "context" nodes like lists.  It now identifies the _topmost_ such node, and borrows its line's indent for computing the bars to show.  Note that `indent-bars-treesit-support` now uses a list of symbols not strings.  If someone could give the `treesit` branch a test and report back, I'd appreciate.   My current config:


```elisp
(use-package indent-bars
  :load-path "~/code/emacs/indent-bars"
  :custom
  (indent-bars-treesit-support '((python argument_list parameters
					 list list_comprehension
					 dictionary dictionary_comprehension
					 parenthesized_expression subscript)))
  :hook ((python-base-mode yaml-mode) . indent-bars-mode))
```

**Comment by jdtsmith** [comment]
New development including treesitter support is on the `dev` branch; please test the treesitter support, and add your relevant config to the [Wiki](https://github.com/jdtsmith/indent-bars/wiki).

**Comment by jdtsmith** [comment]
FYI the most recent development version makes some progress for deep list-nesting.  If `indent-bars-no-descend-lists` is enabled (as it is by default), bars between outer and inner list contexts will be _skipped_ (not displayed).  Please test and let me know of any issues.
