### ISSUE TITLE
Using | as no stiple char

### ISSUE THREAD

**Issue by jessy836** [jdtsmith/indent-bars#90]
I want to use | as no stipple char in tty. If i understand correctly, the idea is to  set indent-bars-no-stipple-char with the unicode of char I want to use. I tryed to do (setq indent-bars-no-stipple-char 124) but no think changed. I checked with C-h v indent-bars-no-stipple-char and it's value is 124, but indent-bars don't display | in emacs in tty.

**Comment by jdtsmith** [comment]
Did you do this from customize, or `M-x indent-bars-reset` afterwards?

**Comment by jessy836** [comment]
> Did you do this from customize, or `M-x indent-bars-reset` afterwards

Thanks, I didn't know about `indent-bars-reset`, I tryed to do `M-x indent-bars-mode` two time to disable then reenable indent bars mode but it didn't applyed the change. But with `indent-bars-reset` it works !

**Comment by jdtsmith** [comment]
If you use setopt or customize interface it will do it for you.
