### ISSUE TITLE
in shell-script-mode tabs appear at 4 spaces, despite having tab-width set to 2

### ISSUE THREAD

**Issue by paaguti** [jdtsmith/indent-bars#91]
I have
```
(setq-default 
  tab-width 2
  indent-tabs-mode nil)
```
But indent-bars appear every 4 spaces:
![image](https://github.com/user-attachments/assets/68c0a8fa-9a04-4d58-a10f-482b012c0fbe)

indent-bars v0.8.2 from elpa

**Comment by jdtsmith** [comment]
What mode is this?  `tab-width` is not usually relevant.  E.g. for `sh-mode` it would be `sh-basic-offset`.  See `indent-bars--guess-spacing`.

**Comment by jdtsmith** [comment]
Let me know if `sh-basic-offset` doesn't fix this.
